### ISSUE TITLE
Reimplement transform based multiplication for f*g when length(f) & length(g) are both large

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#107]
I changed multiplication of f*g to default

        if length(f)≤length(g)
            Multiplication(f,space(g))*g
        else
            Multiplication(g,space(f))*f
        end        

This is almost always much faster than the old transform based multiplication..even though the complexity is worse: min(m^2*n,n^2,m) versus (m+n)*log(m+n).  But when both m and n are very large the old transform is faster again.  

There is a transformtimes() function that encodes the old behaviour.  .* should be overriden for Chebyshev and Fourier to use this based on a heuristic on m and n.

**Comment by ajt60gaibb** [comment]
What does `Multiplication(f,space(g))` do?

**Comment by dlfivefifty** [comment]
f is the function, space(g) is the domain space it operates on.  

For example:


	x=Fun(identity,Chebyshev())
	f= sqrt(1-x^2)			# space(f) == JacobiWeight(0.5,0.5,Chebyshev())
	M=Multiplication(f,space(x))
	domainspace(M)		# Chebyshev()
	rangespace(M)		# JacobiWeight(0.5,0.5,Chebyshev())

**Comment by ajt60gaibb** [comment]
Ah, cool!  Neat.

**Comment by MikaelSlevinsky** [comment]
Using this [script](https://gist.github.com/MikaelSlevinsky/e53237fcf4064bc577c7), I get the following plot comparing Chebyshev multiplication in coefficient space and value space. Black means FFT routine is faster, white means coefficient routine is faster.

![multplot](https://cloud.githubusercontent.com/assets/8176037/7776128/8641271a-00b0-11e5-8be3-1d23d69a0447.png)

**Comment by dlfivefifty** [comment]
Looks like a hyperbolic cross

**Comment by MikaelSlevinsky** [comment]
Yep! The updated [script](https://gist.github.com/MikaelSlevinsky/e53237fcf4064bc577c7) now produces this plot:
![multplot](https://cloud.githubusercontent.com/assets/8176037/7784271/c0c87c1a-0157-11e5-9eb2-d064a8a9ca6c.png)
One set of axes is reversed, but blue means coefficient-based is faster and red means FFT-based is faster.

The black line is the demarcation:

```julia
log10(length(f))*log10(length(g)) = 4
```
and within a small factor, we could probably use this for the periodic function spaces too. Probably within a larger factor BigFloat would show the same phenomenon.

**Comment by MikaelSlevinsky** [comment]
Running the timing tests in `Fourier` supports the same heuristic parameter-space division:
![multplot](https://cloud.githubusercontent.com/assets/8176037/7836749/77ae8b3e-047a-11e5-93ad-8b1743d6e5f9.png)
