### ISSUE TITLE
Should f' be differentiate(f) when f is not an ArraySpace fun?

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#115]
This seems nice, but abuses notation.

**Comment by MikaelSlevinsky** [comment]
I'm in favour of this to the point where every other use of ' should be changed to something else.

This would make it possible to use Julia's string parser on ODEs as you would write it on the board.

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
So you think ' of complex function should just be derivative?

How about .' remains transpose (for arrayspace) and ' is derivative.  If anyone wants conj transpose they can just do conj(F).'

**Comment by dlfivefifty** [comment]
For the second part, are you proposing a chebop like syntax? Not sure string parsing is necessary since it would be easier to do something like

L=Operator((x,f)->f''+f'+x*f)

Where the anonymous functions are called by some type that overloads ' to return Derivative.

**Comment by MikaelSlevinsky** [comment]
Well I was referring to the code generation snippets that I'm working on for the special function overrides, but ya, the ' makes the syntax so much lighter. In those cases D appears but also the derivatives of the inner Fun, and all 2-point BVPs can be written in the same block by parsing the ODE and the RHS.

Not convinced that the Operator override above is necessary until/unless there's AD for nonlinearity.

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
Can you give an example form special functions of the two syntaxes: current and proposed?  Can’t quite picture what you have in mind.

	I suppose nonlinear operators need to be specified using anonymous functions like  

	(x,f)->f’’+x*f + f^2

??

**Comment by MikaelSlevinsky** [comment]
I guess it's only a minor simplification in notation. One of the current blocks looks like this:

```julia
for (op,ODE,RHS,growth) in ((:(Base.exp),"D-fp","0fp",:(real)),
                            (:(Base.log),"f*D","fp",:(real)),
                            (:(Base.asin),"sqrt(1-f^2)*D","fp",:(imag)),
                            (:(Base.acos),"sqrt(1-f^2)*D","-fp",:(imag)),
                            (:(Base.atan),"(1+f^2)*D","fp",:(imag)),
                            (:(Base.asinh),"sqrt(f^2+1)*D","fp",:(real)),
                            (:(Base.acosh),"sqrt(f^2-1)*D","fp",:(real)),
                            (:(Base.atanh),"(1-f^2)*D","fp",:(real)),
                            (:(Base.erfcx),"D-2f*fp","-2fp/sqrt(π)",:(real)),
                            (:(Base.dawson),"D+2f*fp","fp",:(real)))
    L,R = parse(ODE),parse(RHS)
    @eval begin
        function $op{S<:Ultraspherical,T}(f::Fun{S,T})
            g=chop($growth(f),eps())
            xmin=g.coefficients==[0.]?first(domain(g)):indmin(g)
            xmax=g.coefficients==[0.]?last(domain(g)):indmax(g)
            opfxmin,opfxmax = $op(f[xmin]),$op(f[xmax])
            opmax = maxabs((opfxmin,opfxmax))
            if abs(opfxmin) == opmax xmax,opfxmax = xmin,opfxmin end
            D=Derivative(space(f))
            fp=differentiate(f)
            B=Evaluation(space(f),xmax)
            ([B,eval($L)]\[opfxmax/opmax,eval($R)/opmax])*opmax
        end
    end
end
```

and with the ', the proposed block would look like this:

```julia
for (op,ODE,RHS,growth) in ((:(Base.exp),"D-f'","0f'",:(real)),
                            (:(Base.log),"f*D","f'",:(real)),
                            (:(Base.asin),"sqrt(1-f^2)*D","f'",:(imag)),
                            (:(Base.acos),"sqrt(1-f^2)*D","-f'",:(imag)),
                            (:(Base.atan),"(1+f^2)*D","f'",:(imag)),
                            (:(Base.asinh),"sqrt(f^2+1)*D","f'",:(real)),
                            (:(Base.acosh),"sqrt(f^2-1)*D","f'",:(real)),
                            (:(Base.atanh),"(1-f^2)*D","f'",:(real)),
                            (:(Base.erfcx),"D-2f*f'","-2f'/sqrt(π)",:(real)),
                            (:(Base.dawson),"D+2f*f'","f'",:(real)))
    L,R = parse(ODE),parse(RHS)
    @eval begin
        function $op{S<:Ultraspherical,T}(f::Fun{S,T})
            g=chop($growth(f),eps())
            xmin=g.coefficients==[0.]?first(domain(g)):indmin(g)
            xmax=g.coefficients==[0.]?last(domain(g)):indmax(g)
            opfxmin,opfxmax = $op(f[xmin]),$op(f[xmax])
            opmax = maxabs((opfxmin,opfxmax))
            if abs(opfxmin) == opmax xmax,opfxmax = xmin,opfxmin end
            D=Derivative(space(f))
            B=Evaluation(space(f),xmax)
            ([B,eval($L)]\[opfxmax/opmax,eval($R)/opmax])*opmax
        end
    end
end
```

**Comment by dlfivefifty** [comment]
Oh ok I understand what you mean by string parsing now.  Nice use of eval!  Didn’t know that was possible

**Comment by dlfivefifty** [comment]
I implemented this.  Use conj(f.') if you want ctranspose(f).
