### ISSUE TITLE
Piecewise aliasing check may break since random point is only in one component

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#118]

**Comment by goretkin** [comment]
aliasing would be if g had been the zero function, right? 

```julia
julia> f = Fun(x->sin(3000x),Interval())
Fun{Ultraspherical{0},Float64}([6.9123e-16,0.024614,2.00485e-16,0.0245932,-3.80905e-16,0.0245514,-1.56165e-16,0.0244885,-5.02903e-16,0.024404  …  -3.83374e-16,-7.3302e-16,8.10116e-16,-2.56762e-16,3.88578e-16,1.1988e-15,-3.38271e-16,2.54271e-16,4.52763e-16,-9.52131e-16],Ultraspherical{0}(Interval{Float64}(-1.0,1.0)))

julia> f.coefficients[:] = 0.;

julia> f.coefficients[300] = 2.0;

julia> g = Fun(x->f[x],Interval())
Fun{Ultraspherical{0},Float64}([-1.4368e-15,1.78116e-15,-3.94716e-15,-5.45003e-15,-5.99497e-15,-3.81497e-15,-5.78823e-15,-3.7787e-15,-2.95757e-15,-8.12579e-15  …  -1.00247e-15,2.60289e-14,-6.53816e-16,2.32211e-14,9.71093e-16,2.31197e-14,1.81013e-15,2.24712e-14,-7.52087e-16,2.25431e-14],Ultraspherical{0}(Interval{Float64}(-1.0,1.0)))

julia> g.coefficients[300]
2.0000000000000084

julia> length(g), length(f)
(512,32769)
```

**Comment by dlfivefifty** [comment]
Aliasing is how cos(100x) looks like 1 if you underresolve

	Fun(t->cos(100t),Fourier,10).coefficients == [1.0,0.0,-0.0,-0.0,0.0,0.0,-0.0,-0.0,0.0,-0.0]


The constructor double checks a random point to ensure the approximation matches there.  But a single random point is not enough when there are multiple components.

**Comment by ajt60gaibb** [comment]
One needs to take a random point per piece. I am not sure how you are constructing piecewise polynomial approximations, but I was expecting it to resolve each piece independently and then concatenate them together.

**Comment by dlfivefifty** [comment]
That would be a more efficient way to do it but requires specializing the constructor.  Instead, ArraySpace just overrides points and transform, calling the standard constructor.  Here the points are a union of points in each subpiece and the transform then splits the values by piece, calls transform for each subpiece, then interlaces the coefficients.

	The benefit of this approach is “PiecewiseSpace” is just another space for most components (\, etc.), so that no special treatment is required.  The cost is more coefficients than needed when the resolution on one piece is << the resolution on the other piece.  The other cost is having to repeatedly interlace and deinterlace coefficients.  But doing \ in infinite-dimensions seems to only make sense with this interlacing approach.

	A simple work around to this problem is that each space overrides a “checkpoints” routine, which defaults to a single random point in the domain, but then piecewise can return one rand point per subpiece.

**Comment by ajt60gaibb** [comment]
Right, got it. Thanks.  `checkpoints()` sounds OK.
