### ISSUE TITLE
Should 2*Chebyshev()  be short hand for ArraySpace(Chebyshev(),2)?

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#120]
Want to get space manipulation syntax mathematically correct.  Right now there's only (using Chebyshev() as placeholder for general space)

  Chebyshev() ⊗ Chebyshev()

for tensor product in rectangle, which is mathematically correct I think.  Not sure if Chebyshev()^2 should mathematically be the same thing.  And if n*Chebyshev() should be ArraySpace.  Not sure how one would do a 2x2 ArraySpace(Chebyshev(),2,2),  I guess 

(2Chebyshev()) ⊗ (2ConstantSpace())

Can't decide if this is sexy or perverted (or both...)

**Comment by ajt60gaibb** [comment]
`2Chebshev()` seems too weird to me.     I can tell you what happens in MATLAB for vectors: 

Tensor products:    `kron(v, v')`  so I like  `Chebyshev() ⊗ Chebyshev()` 
Array-valued:  repmat(v, m,n), so does  `ArraySpace(Chebyshev(),m,n)` or `repSpace(Chebyshev(),m,n)` makes sense?

A 2x3x5 ArraySpace could then be `repSpace(Chebyshev(),2,3,5)`... 

Overloading `⊗` to have a nonstandard mathematical meaning is a little too 
strange for me.  I know you like `⊗`.

**Comment by dlfivefifty** [comment]
Which usage of ⊗ is nonstandard mathematical? Aren’t both spaces (Chebyshev()⊗Chebyshev()) and operators (Derivative()⊗Derivative()) usage mathematically correct?  I think thats the only places I use it.  (I got rid of Interval()⊗Interval() since that was wrong.)
 

	But I think Chebyshev()*Chebyshev() is also mathematically correct, since ⊗ is just * with some extra structure
