### ISSUE TITLE
Add type to FunctionSpace and Operator/Fix Evaluation functional over complex intervals

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#122]
This will allow \ for BigFloat.

**Comment by MikaelSlevinsky** [comment]
This might be useful:

```julia
Base.real{T<:Real}(::Union(Type{T},Type{Complex{T}})) = T
```

That way, things like `eps{T<:Number}(::Type{T}) = eps(real(T))` can be defined.

**Comment by goretkin** [comment]
It looks like `Operator` is already parametrized by a `T` which appears to serve this purpose. Is that correct?

**Comment by dlfivefifty** [comment]
Yes but the subtypes don’t necessarily support arbitrary types.  E.g.

Derivative{Chebyshev} <: BandedOperator{Float64}


since the basis is real (this is actually a bug since the derivative is complex on complex intervals).  So we want 

Derivative{Chebyshev,T} >: BandedOperator{T}

where T is chosen as part of the space promotion.    This would make life a little easier as operators would always be the same type, where now we mix BandedOperator{Float64} and BandedOperator{Complex{Float64}}.

**Comment by dlfivefifty** [comment]
I started adding a type to FunctionSpace but I'm not sure its the right way forward.  There are some issues with typed typealias,  so that defining

typealias Chebyshev{T} Ultraspherical{0,T}

doesn't allow defining Chebyshev().  It also makes the code more complicated, since overrides are now of the form Fun{Chebyshev{T},T} instead of Fun{Chebyshev,T}.  

Also, I can't think of an operation where the type of the function space needs to be known.  The only exception is domain/rangespace of Operators.  Maybe these should be a tuple with types?

**Comment by dlfivefifty** [comment]
The following now calculates exp(1) to 60 digits in 0.0025 seconds in fix-operatortype branch:

d=Interval{BigFloat}(0,1)
D=Derivative(d)
u=linsolve([ldirichlet(d),
    Derivative(d)-I],[1];tolerance=10e-60)
u[1]-exp(big(1.0))

**Comment by dlfivefifty** [comment]
And now this works too :)

d=Interval{BigFloat}(-100,40)

x=Fun(identity,d)
D=Derivative(d)
@time u=linsolve([dirichlet(d),
    D^2-x],[airyai(big(-100.0)),0];tolerance=10e-60)

u[0]-airyai(big(-0.0))

**Comment by MikaelSlevinsky** [comment]
That's sensationally fast! I'm gathering timings from comparables in BigFloat. By linsolve, I'm finding 0.0038 seconds:

```julia
d=Interval{BigFloat}(0,1)
D=Derivative(d)
[ldirichlet(d),D-I]\[1];[ldirichlet(d),D-I]\[1];
@time for i=1:100
    [ldirichlet(d),D-I]\[1]
end
```

By the contructor, I'm finding 0.058 seconds:

```julia
d=Interval{BigFloat}(0,1)
Fun(exp,d);Fun(exp,d);
@time for i=1:100
    Fun(exp,d)
end
```

By the [SincFun.jl](https://github.com/MikaelSlevinsky/SincFun.jl) package (a work-in-progress), I'm finding 0.04 seconds:

```julia
using SincFun
d=Finite(big(0.0),big(1.0))
sincfun(exp,d);sincfun(exp,d);
@time for i=1:100
    sincfun(exp,d)
end
```

By the timings supplied in [http://arxiv.org/abs/1407.2802](http://arxiv.org/abs/1407.2802) at best 0.05 seconds for all examples in Table 2. These seem to be on par with the construction timings, so this might be due to using Maple instead of Julia.

Also, the construction seems to scale much worse with the number of digits. With 1,000 digits, I'm finding ~0.047 seconds for linsolve, ~16 seconds for ApproxFun construction and ~8 seconds for SincFun construction.

When we end up using fftw routines instead of the fftBigFloat and fftGeneric here, I believe we'll see an approximate 7-fold speedup (quoting timings from @goretkin), so I think resolution of Funs via linsolve will have its place for functions with a low bandrange.

**Comment by MikaelSlevinsky** [comment]
I know this is really new, but could you explain what these lines in FunctionSpace.jl mean?

```julia
immutable RealBasis end
immutable ComplexBasis end
immutable AnyBasis end

coefficient_type{T<:Complex}(::Type{ComplexBasis},::Type{T})=T
coefficient_type{T<:Real}(::Type{ComplexBasis},::Type{T})=Complex{T}
coefficient_type{T}(::Type{RealBasis},::Type{T})=T

Base.eltype(::RealBasis)=Float64
Base.eltype(::ComplexBasis)=Complex{Float64}
Base.eltype(::AnyBasis)=Number

Base.eltype(::Type{RealBasis})=Float64
Base.eltype(::Type{ComplexBasis})=Complex{Float64}
Base.eltype(::Type{AnyBasis})=Number
```

**Comment by dlfivefifty** [comment]
I Added comments to the file.  I’ve been bad about commenting code so please file issues about any parts that are confusing.

## 
# "enum" types used for whether the basis is
# Real or Complex.  AnyBasis is used when the answer
# is unknown.  
##

immutable RealBasis end
immutable ComplexBasis end
immutable AnyBasis end


# coefficient_type(basis,valuetype) gives the type for coefficients
# for basis of type RealBasis/ComplexBasis and valuetype
# giving the type of function values
coefficient_type{T<:Complex}(::Type{ComplexBasis},::Type{T})=T
coefficient_type{T<:Real}(::Type{ComplexBasis},::Type{T})=Complex{T}
coefficient_type{T}(::Type{RealBasis},::Type{T})=T


#
# eltype for RealBasis/ComplexBasis gives the
# default type.  Maybe should be defaulteltype?
#

Base.eltype(::RealBasis)=Float64
Base.eltype(::ComplexBasis)=Complex{Float64}
Base.eltype(::AnyBasis)=Number

Base.eltype(::Type{RealBasis})=Float64
Base.eltype(::Type{ComplexBasis})=Complex{Float64}
Base.eltype(::Type{AnyBasis})=Number

**Comment by MikaelSlevinsky** [comment]
With the FFT sped up, by the contructor I'm finding 0.01 seconds now:
```julia
d=Interval{BigFloat}(0,1)
Fun(exp,d);Fun(exp,d);
@time for i=1:100
    Fun(exp,d)
end
```
