### ISSUE TITLE
Chebyshev should be different than Ultraspherical{0} with simple conversion?

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#123]
Right now julia can't have constructors for typealiases with parameters.  This is preventing the addition of types to FunctionSpace, since then Chebyshev requires a parameter.  If it was its own type this issue would go away.

**Comment by MikaelSlevinsky** [comment]
Isn't there a normalization difference between the mathematical definitions of Ultraspherical{0} and Chebyshev? Not that this is enough for me to form an opinion...

**Comment by dlfivefifty** [comment]
I don't think Ultraspherical{0} is defined, though geigenbauir is..

**Comment by ajt60gaibb** [comment]
Yes, Ultraspherical{0} is not defined.

**Comment by MikaelSlevinsky** [comment]
I guess there's not harm leaving it the way it is then.

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
I think it's better to wait to 0.4 when typealias can be overriden, and then 

typealias Chebyshev{T} Ultraspherical{0,T}
Chebyshev(d)=Chebyshev{eltype(d)}(d)

will work fine.
