### ISSUE TITLE
\ gives wrong structure for matrix rhs

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#126]
```
B=ldirichlet()

[B,D]\[0. 0.; Fun(exp) Fun(cos)]
```

Returns column vector fun ( ArraySpace{*,1} ) but should be a row vector of funs or row vector fun

**Comment by dlfivefifty** [comment]
Need to remember how to quote out text...

**Comment by goretkin** [comment]
(three back-ticks ```, edited it)

**Comment by dlfivefifty** [comment]
This was fixed
