### ISSUE TITLE
Implement algebra for LowRankPertOperator

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#127]
There's no reason operators need to be banded in \, and there might be some cases where almost banded would be useful. This would be the case where the fill in is given by a functional (using SumFunctional to represent a linear combination of other functionals.)  So in addition to 

   addentries!

that writes the banded entries, there would need to be some access to the fill information.

**Comment by dlfivefifty** [comment]
Actually, this might not be a good idea because doing algebra on these operators is difficult.  Maybe better to keep it how it is.

**Comment by MikaelSlevinsky** [comment]
Have you considered having a `SliceOperator` like `SliceSpace`? Just experimenting and this might address overdetermined systems #80 and help in resolving functions through singular points. Some kind of least squares block at Chebyshev points on top of the infinite operator. Trivially:

```julia
d = Interval()
L = Derivative(d) - I
B = ldirichlet(d)
Bextra = rdirichlet(d)
m=20;A = [B[1:m]'; Bextra[1:m]'; full(L[2:m-1,1:m])]
A\[exp(-1),exp(1),zeros(m-2)]
```

works the same as `[B,L]\[exp(-1)]`.

**Comment by MikaelSlevinsky** [comment]
I guess it's not least squares, just interpolation using an arbitrarily high number of terms.

**Comment by dlfivefifty** [comment]
There is a SliceOperator in src/Operators/StrideOperator.jl

**Comment by MikaelSlevinsky** [comment]
Oops! I guess it would be hard to develop a heuristic or an estimate for the number of extra conditions to include, as this would have to happen before linsolve?

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
My feeling is telling well posedness apriori is inheritently ill posed. Thinking about eigenfunctions makes this true I think. (Dirichlet at an eigenvalues is ill posed)

**Comment by dlfivefifty** [comment]
I've added this.  As LowRankOperator <: AlmsotBandedOperator gets fleshed out, this will be made more useable.

**Comment by dlfivefifty** [comment]
Just need a good name for the operator that consists of a list of functionals and a BandedOperator, since AlmostBandedOperator is abstract.

**Comment by dlfivefifty** [comment]
The code below now works.  I've added LowRankOperator which is an outer product of Funs with Functionals, and LowRankPertOperator, which represents a BandedOperator + LowRankOPerator.  I believe this is all that is needed for AlmostBandedOperator: algebra can be done on this since we have e.g.

(A+UV')*(B+WX') = AB + AWX'+UV'B + UV'WX' = AB + [AW U U]*[X';V'B;V'WX']

is also a BandedOperator + LowRankOperator.


L=Operator((x,u)->[u(-10.);u(5.);u''-x*u-u(0.1)],[-10.,5.])
u=L\[1.,0.]
ApproxFun.plot(u)
