### ISSUE TITLE
Should circles be mapped domains from periodic intervals?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#138]

**Comment by dlfivefifty** [comment]
Not sure I understand the question...

**Comment by MikaelSlevinsky** [comment]
Maybe I've been confused by the required assertions (especially in operators' addentries!) checking either `isa(d,PeriodicInterval)` or `isa(d,Circle)`.

**Comment by dlfivefifty** [comment]
Ohhhh, I guess you mean MappedSpace?  So that the implementations can be different?
