### ISSUE TITLE
Elegant partial differentiation/Does d/d(r^2) make sense numerically

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#152]
Trying to decide the best way to do partial derivatives when there are multiple coordinate systems.  Ideally something like this in the disk would work:

r=Fun(norm,Disk());θ=Fun(angle,Disk())
Dr=Derivative(Disk(),r);Dθ=Derivative(Disk(),θ)

Δ=(1/r)*Dr*(r*Dr)+(1/r^2)*Dθ^2

But for this to make sense, I need to understand differentiation with respect to a "Fun".  (The last sentence sounds suspiciously familiar to a previous issue...)  

One can hack it for the disk, but for consistency, if the previous example makes sense than so should

f=Fun(exp)
x=Fun(identity)
D=Derivative(space(f),x^2)

Clearly D*(x^(2k)) should be k*x^(2k-2), and this would probably translate to non-integer k.  But I'm not sure if I know how to push this further.  

Some sort of "think of it in terms of Jacobi operators and blah blah blah and then it's obvious" would be ideal.

**Comment by jwmerrill** [comment]
One observation is that `d/dg(x) f(x) = d/dx f(g^{-1}(x))`, so if you can invert a Fun, you can use this identity to take derivatives w.r.t. it.

**Comment by dlfivefifty** [comment]
Good point, maybe I should add a function inverse routine.  

This is probably pretty straightforward using the existing "extrema" calls with JacobiWeight for square root singularities and PiecewiseSpace for multiple valued functions.

**Comment by jwmerrill** [comment]
> One observation is that `d/dg(x) f(x) = d/dx f(g^{-1}(x))`

Sorry, this is actually erroneous. I had remembered seeing some discussion of differentiation with respect to a function in the literature on fractional calculus, and went skimming through some references to try to refresh my memory. I took a too-quick look at eq. 14.1 in http://www.rowan.edu/open/depts/math/osler/FracDeriv%26SpecFctns.pdf and thought it was equivalent to the above, but it isn't.

**Comment by dlfivefifty** [comment]
Hmm, shouldn’t df/dg just be (at least formally)

		h(t)=f(g^{-1}(t))
		h’(g(x))

This at least works for the example

	d(x^(2k))/dx^2 should be kx^(2k-2)

**Comment by jwmerrill** [comment]
Yes, that seems like the right way to state it.

In the case of 1D functions, at least, you can also use the chain rule to say

`df(x)/dg(x) = df(x)/dx dx/dg(x) = f'(x)/g'(x)`

and this also works for the `d(x^(2k))/dx^2` example, but I think some care is required to extend this to partial derivatives of multivariate functions.
