### ISSUE TITLE
LowRankFuns should have a 2D space

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#161]
2D function spaces are more than the tensor product of their component spaces, and can be enriched with e.g. diagonal singularities as in SIE.jl.

**Comment by dlfivefifty** [comment]
I don't see how low rank fun makes sense in any spaces other than tensor product spaces, as they are built out of sums of outer products of functions

**Comment by MikaelSlevinsky** [comment]
I'm completely happy if they're in a `TensorSpace`, but currently they're only parameterized by the two 1D spaces.

**Comment by dlfivefifty** [comment]
Oh OK, that’s reasonable.  Though probably 2D has to settle first a bit, then we can reorganize it.

**Comment by MikaelSlevinsky** [comment]
Now that I understand the 2D spaces a little better, I think this issue was raised by mistake.

Some of the LowRankFun methods take the `TensorSpace`, so all is well.
