### ISSUE TITLE
Add alternative to using complex numbers for representing 2D domains

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#162]
Right now 

Circle()

represents both a circle in the complex plane and in 2D.  similarly the boundary of Interval()^2 is a piecewise interval in the complex plane.  These two concepts should be distinct.  

Should 2D be a tuple?

**Comment by dlfivefifty** [comment]
I started thinking about proper 2D intervals instead of overloading intervals in the complex plane: e.g.  Interval((1,2),(3,4)) instead of Interval(1+2im,3+4im).  

Interval(1+2im,3+4im) is a Domain{Complex{Float64},1} and an Interval()^2 is a Domain{Float64,2}.  Should Interval((1,2),(3,4)) be

Domain{(Float64,Float64),1}
Domain{Float64,2}     or
Domain{(Float64,Float64),2}

**Comment by MikaelSlevinsky** [comment]
I can see how this would be helpful. For the typing, `Interval((a,b),(c,d))` is definitely a one-dimensional domain, and probably carrying the type tuple would be ok, since then a and c or b and d or all could be complex as well.

Should `Interval((-1.0,0.0),(1.0,0.0))^2` be the square `Interval((-1.0,0.0),(1.0,0.0))*Interval((0.0,-1.0),(0.0,1.0))` or the `ProductDomain` with itself?

Does an `Interval((a,b),(c,d))` have a `complexlength` (for compatibility with certain operators) as well as a `length`? Certainly gets complicated.

**Comment by dlfivefifty** [comment]
> On 21 Apr 2015, at 8:33 pm, Richard Mikael Slevinsky <notifications@github.com> wrote:
> 
> I can see how this would be helpful. For the typing, Interval((a,b),(c,d)) is definitely a one-dimensional domain, and probably carrying the type tuple would be ok, since then a and c or b and d or all could be complex as well.
> 
> Should Interval((-1.0,0.0),(1.0,0.0))^2 be the square Interval((-1.0,0.0),(1.0,0.0))*Interval((0.0,-1.0),(0.0,1.0)) or the ProductDomain with itself?
> 
> 


This should be a square in R^4.  Interval(-1,1)*Interval((-1,0.),(1.,0.)) then would be a square in R^3.




> Does an Interval((a,b),(c,d)) have a complexlength (for compatibility with certain operators) as well as a length? Certainly gets complicated.
> 

Not really sure what “complexlength” actually means...

**Comment by dlfivefifty** [comment]
Hmm I think Interval([a,b],[c,d]) is better:  addition is not implemented on tuples.

**Comment by dlfivefifty** [comment]
Though this has the consequence that the dimension can’t be inferred from type 😔

**Comment by dlfivefifty** [comment]
This works now

	d=Interval([1.0,2],[3.0,6])
	f=Fun(x->exp(-x[1]^2-2x[2]^2),d)

Ideally we would want to also be able to do

	f=Fun((x,y)->exp(-x^2-2y^2),d)

But right now, since the space can’t see the domain, this would require making the existing constructor more complicated.  I think it’s better to put off expanding on this change until 0.4, when the space type will include the domain type as a template variable.

**Comment by MikaelSlevinsky** [comment]
Hi,

I was using an Interval constructor which created array of intervals from two endpoint vectors. This made working with UnionDomains of Intervals and Circles quite easy:
```julia
a,b = rand(10),rand(10)
c,r = rand(10),rand(10)
∪(Interval(a,b))∪∪(Circle(c,r))
```
I suppose I could always do:
```julia
∪(map(Interval,a,b))
```
but I'd be happier if the previous ability was restored.

**Comment by MikaelSlevinsky** [comment]
Alternatively, I could use tuples since I'm just assembling the domains and not doing any arithmetic on the endpoints. Thoughts?

**Comment by dlfivefifty** [comment]
I removed this just because constructors should return the type, but maybe it can be added back.

**Comment by dlfivefifty** [comment]
This seems like a better syntax:

	UnionDomain(Interval,a,b)

or 

	UnionDomain(Circle,a,b)

as the type returned is a Union domain.    Then one also doesn’t have to write constructors for future types.

**Comment by MikaelSlevinsky** [comment]
Thanks for bringing that up. Yep, good to stick with the constructor => type rule. In @edb063d7a8905fff20f5ecac489c0341f08011be, I've implemented the union symbol to deal with cases like:
```julia
∪(Circle,1.0)
∪(Interval,-1,1)
∪(Circle,[0.0,1.0],[2.0,3.0])
∪(Interval,{[1,2],[3,4]},{[5,6],[7,8]})
```
Imo, it makes sense that the union of a single domain is that domain, so using the symbol instead of a constructor for UnionDomain still follows the constructor => type rule.

**Comment by dlfivefifty** [comment]
Sounds good!  In 0.4 we'll also be able to use Domain(...) as the constructor.

**Comment by dlfivefifty** [comment]
This has been implemented:

```julia
julia> f=Fun((x,y)->exp(x+y),Interval((0,0.),(1,1.)))
Fun([3.4415238691253354,3.0725234451419365,0.7380008479667992,0.12052005327474004,0.014880528318358996,0.0014758267278679308,0.00012226103967960184,8.694251715223477e-6,5.415156664654856e-7,3.000105597462556e-8,1.49665755157517e-9,6.790144264878533e-11,2.824647334188317e-12,1.0843584770410246e-13],Chebyshev(【Vec(0.0,0.0),Vec(1.0,1.0)】))

julia> f(0.5,0.5)
2.718281828459049
```
