### ISSUE TITLE
Integral Constraints?

### ISSUE THREAD

**Issue by idontgetoutmuch** [ApproxFun/ApproxFun.jl#168]
The referenced paper "A. Townsend & S. Olver (2014), The automatic solution of partial differential equations using a global spectral method, arXiv:1409:2789" tantalisingly mentions the possibility of integral constraints. Have these been implemented? I have an example if that would be helpful.

**Comment by dlfivefifty** [comment]
Yep, just use the DefiniteIntegral functional

**Comment by dlfivefifty** [comment]
Actually, DefiniteIntegral is current limited to square-root singularity spaces.  But it can be done via the following:

S=Chebyshev()
Q=Integral(S)
B=(Evaluation(S,1.)-Evaluation(S,-1.))*Q


We can leave this issue open until this becomes implemented as the default for DefiniteIntegral

**Comment by dlfivefifty** [comment]
A default DefiniteIntegral is now implemented.
