### ISSUE TITLE
plan_transform for every space

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#169]
I can think of some ways to use this in 2D. For instance, all the transform! routines in the TensorSpace.jl file could be planned, since they're all the same size. Also, it might be useful for the low rank constructor.

**Comment by dlfivefifty** [comment]
transform! vs transform should also be unified.

**Comment by MikaelSlevinsky** [comment]
The main goal of this issue was to expose FFTW's plans. Having the package function `plan_transform` allows for the following speed-up in 2D transforms:
```julia
julia> using ApproxFun # On an old branch

julia> M = rand(500,500)+im*rand(500,500);

julia> @time ApproxFun.transform!(Chebyshev()⊗Laurent(),M);
elapsed time: 0.122417776 seconds (41246408 bytes allocated, 35.85% gc time) # best time out of 5


julia> using ApproxFun # On development/master

julia> M = rand(500,500)+im*rand(500,500);

julia> @time ApproxFun.transform!(Chebyshev()⊗Laurent(),M);
elapsed time: 0.027798852 seconds (35493304 bytes allocated) # best time out of 5
```
Access to this new function allows many `Fun`s to be constructed in the same space and the same length by planning once and taking values to coefficients with the same plan. For another non-trivial speed-up, see [here](https://github.com/ApproxFun/SIE.jl/blob/master/src/GreensFun/evaluation.jl).

Plans don't have to be FFTW functions. In fact, for orthogonal polynomials the plan_transform just precomputes nodes and weights of the Gauss quadrature rule for the Vandermonde matrix (unless faster algorithms are implemented).

Some of the more exotic spaces don't have plans yet, but this is at the point of diminishing returns. How to close?

**Comment by dlfivefifty** [comment]
I think this is done.
