### ISSUE TITLE
Do all development in a new "development" branch and leave "master" as a (basically) release-quality version

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#178]
I'll start this after the next tagged version (I'm currently working on getting all the examples working again)

**Comment by MikaelSlevinsky** [comment]
I think we should replace syntax with poetic versions in the readme. Nobody cares what the operators are called, but if it looks like it does on the board, that's #winning.

**Comment by MikaelSlevinsky** [comment]
Does the build test get checked for non-master branches? I can't remember.

Should the new development branch be the default? (I think so, but it's complicated by the fact that we don't have a website, so the initial readme on the default branch is the first thing ppl see)

Is the plan to also have off-shoot branches from development, as in Chebfun, or if they're incremental changes they can be pushed to development directly?

**Comment by dlfivefifty** [comment]
I think the plan is that master should always pass all tests, where development is less strict.

Right now I occasionally have to check things in that break the tests to finish at work.

So well use development as the primary source, and occasionally merge to master when its stable. Master is the branch we want others to use, and it's read me is the real read me.
