### ISSUE TITLE
Add transform to Hermite space

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#179]
Should Hermite polynomials be in this package? Banded derivatives don't change the basis and Multiplication can be done by recurrence. There could also be a parameterized HermiteWeight with a Gaussian envelope so that we can have differential operators with polynomial coefficients, yet expect the solution with a Gaussian envelope inferred from a RHS.

A couple things would need reworking: `PolynomialSpace` is technically not always an `IntervalSpace`, and with Hermite, there is another interpretation to the real line than the currently implemented `tan` mapping.

A drawback is no fast transform, but maybe this won't matter in practice due to the O(n^(1/2)) cutoff for weights smaller that ~1e-308.

**Comment by dlfivefifty** [comment]
I just added Hermite.jl, which I started a couple weeks ago which does this.

**Comment by dlfivefifty** [comment]
I think IntervalSpace should be removed.  This can come back when FunctionSpace includes the Domain.

**Comment by dlfivefifty** [comment]
This is implemented already I guess
Fun(x->x+x^2,Hermite())[4.]

**Comment by dlfivefifty** [comment]
Also this:

Fun(x->(x+x^2)*exp(-x^2),GaussWeight(Hermite(),1))

**Comment by MikaelSlevinsky** [comment]
It would be cool to solve ODEs/differential eigenvalue problems on the whole real line with coefficients in `Hermite` and the solution in `GaussWeight`. This would have the same flavour as solving SIEs in `JacobiWeight` but with only diagonally singular kernels, otherwise in `Chebyshev`: a kind of promotedomainspace ... promoterangespace argument.

**Comment by ajt60gaibb** [comment]
There is a debate about Hermite versus a simple change of variables for dealing with problems on the whole real line. Do you have any thoughts about this?

**Comment by dlfivefifty** [comment]
Or for that matter truncating the domain: if you have Gaussian decay then its effectively finite.

Though when the operator is L^2 self-adjoint then GaussWeight(1/2,Hermite()) may be useful as it forms an orthogonal basis.

Another case where its useful is lanczos for calculating recurrence relationships: here you are getting higher and higher polynomial times Gauss weight, and using maps causes large error.

**Comment by ajt60gaibb** [comment]
I guess if you want to discretize to a Hermitian matrix, yeah. That's a good argument for GaussWeight(1/2,Hermite()). 

I am not sure I fully understand why mappings do not work for high degree polynomials times Gauss weight... I thought Chebfun used this technology.   I know that one cannot take derivatives when using maps, as Mark Richardson says in his thesis.

**Comment by dlfivefifty** [comment]
Ok, I think I was thinking of rational maps (which is what Line() currently uses), but sinc maps might be better.

**Comment by ajt60gaibb** [comment]
I think sinc maps are optimal in some sense...

**Comment by ajt60gaibb** [comment]
I think sinc maps are optimal in some sense...

**Comment by dlfivefifty** [comment]
Probably change the name of the issue if it needs to be reopened, since the hermite transform is implemented now.

**Comment by MikaelSlevinsky** [comment]
Regarding approximation theory, there may not be much to be gained from supporting Hermite over mapped or truncated domains. In terms of ODEs, it may be worth investigating which representation is best. Perhaps the bandwidths may be consistently lower in one over the others, or perhaps one's operator entries are cheaper than the others'.

One strike against sinc methods is that the discretisations aren't banded, so far as I know. Puzzlingly, the sinc ansatz is simultaneously both in coefficient space and in value space, due to the discrete orthogonality, sinc(k-j) = delta_{k,j}. There is also the matter of choosing the step size (and conformal maps.....) optimally.

Cheers,

Mikael

**Comment by dlfivefifty** [comment]
I guess I meant “double exponential maps” not “sinc maps”.  Sinc approximation doesn’t really fit into the ApproxFun framework since it requires discretizing space.

**Comment by dlfivefifty** [comment]
This works now:

Fun(x->x+x^2,Hermite())
