### ISSUE TITLE
Make Int a valid type for Fun

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#180]
Right now Ints are converted to Floats at various places, inconsistently, and the type is also assumed to be a float, usually via eps(T).  We should remove all unnecessisary converting to floats.

**Comment by goretkin** [comment]
From what I remembered, the reason those conversions were in place is so that users could type in, for example, `Fun(sin,[1,2])` instead of `Fun(sin,[1.,2.])`. What kind of use cases are there for a Fun of type T that isn't  T<:FloatingPoint? rational or fixed-point types?

**Comment by dlfivefifty** [comment]
One use is ints are infinite precision.  The other is I keep typing Fun([1,2],Chebyshev) and having it break..though maybe just convert int arrays to floats is a better solution.

**Comment by goretkin** [comment]
I don't understand what you mean by Ints being infinite precision? That hypothetically `eps(Int64)` should be 0?

**Comment by dlfivefifty** [comment]
I mean the round-off error for int calculation is 0.   So the “precision” of a number in Int format is ∞: you know it is the true number with zero error.

**Comment by goretkin** [comment]
I guess I'm confused about what this would be used for. You mean that the
coefficients of the polynomial are Integral, right? Is that an important
class of polynomials in the area of function approximation?

**Comment by dlfivefifty** [comment]
Not sure… but it just might be an easier task to always support ints (by overloading ApproxFun.eps, etc.) than to always catch ints and convert to floats.

**Comment by MikaelSlevinsky** [comment]
Rationals are also "infinitely" precise, so we may as well support them too. Also, most closed form expansions in orthogonal series have rational coefficients.

**Comment by dlfivefifty** [comment]
That would be cool: \ with rationals to get exact formula.

	Though Given’s rotations won’t work, need to be Gauss elimination.  But I guess with rationals no need to worry about stability!

**Comment by dlfivefifty** [comment]
Actually, after trying to implement this I changed my mind and don't think its worth it.  Rationals should work though.

**Comment by MikaelSlevinsky** [comment]
Rationals might also be tricky because \ is always solving a nearby problem, which might lead to large irreducible ratios approximating short rationals.

Cheers,

Mikael
