### ISSUE TITLE
Add det for operators

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#193]
Just do adaptive qr til diagonal converges.  May only work for I + compact but that's fine

**Comment by dlfivefifty** [comment]
Don't you need to take into account the diagonal of the Conversion from an operators domain to range?

**Comment by MikaelSlevinsky** [comment]
Yep, you are right.

Considering det(I+K), where K is compact with different domain and range spaces, then det(I+K) = det(C+C*K)/det(C). Oddly enough, somewhere in the `LowRankPertOperator/LowRankOperator` construction the U's are getting correctly converted down to Chebyshev (from either Legendre or Ultraspherical), and note also that Conversion(Chebyshev(),Legendre()) isn't working yet.
