### ISSUE TITLE
Operators for finite dimensional spaces

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#201]
This would support operators on finite dimensional spaces.  For example, if a space is a cubic spline, a finite-dimensional derivative would return a quadratic spline.   The derivative operator would be a finite matrix then.

This could be accomplished by giving Operator dimensions:

Operator{T,n,m}

so that 

Functional{T} <: Operator{T,1,∞}
BandedOperator{T} <: Operator{T,∞,∞}

**Comment by MikaelSlevinsky** [comment]
Maybe
```julia
Functionals{T,k} <: Operator{T,k,∞}
Functional{T} <: Functionals{T,1}
```
would help with representing k functionals, including #88.

**Comment by dlfivefifty** [comment]
I think its more accurate to say


	typealias Functionals{T,k} Operator{T,k,∞} 

But I’m not sure that the Functionals is actually needed.  

Note that we can’t do this until 0.4.

**Comment by dlfivefifty** [comment]
Whether the dimensions should be templated is also debatable.  We could just make it a function call.

**Comment by dlfivefifty** [comment]
This is now implemented.
