### ISSUE TITLE
typealias Chebyshev{1} Ultraspherical{0}?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#211]
I'm not even sure this is possible, but it would in principle allow for
```julia
typealias Chebyshev{2} Ultraspherical{1}
```
and then the third and fourth kind polynomials could be `Chebyshev{3}` and `Chebyshev{4}`.

**Comment by dlfivefifty** [comment]
I think it might be better to do


	function Chebyshev(k::Integer,d)
		if k==1
			Chebyshev(d)
		elseif k==2
			Ultraspherical{1}(d)
		elseif k==3
			Jacobi(-0.5,0.5,d) 	# may not have correct normalization
		...
	end

**Comment by MikaelSlevinsky** [comment]
Ok. Is it true then that each kind of Chebyshev polynomial has a fast transform (some form of DCT or DST) at each kind of point, i.e. 16 fast transforms in total?

**Comment by dlfivefifty** [comment]
I think it’s true but not sure how to do it for 3/4 kind

**Comment by ajt60gaibb** [comment]
Yes, sure. This is true.   There are 4 types of Chebyshev polynomials and 4 sets of Chebyshev points.  This gives 16 transforms.  Each one is a diagonally weighted discrete cosine or sine transform.l computed via FFTs.  In Chebfun in the commands chebfun.dct(), chebfun.idct(), chebfun.dst(), and chebfun.idst() I coded up all 16 DCT and DST transforms and their inverses just for this purpose.

**Comment by MikaelSlevinsky** [comment]
Great! This is actually what I wanted from this issue.

**Comment by dlfivefifty** [comment]
I guess the chebfun case callse fft/ifft?  Probably all 16 can be made more efficient by calling FFTW….

**Comment by ajt60gaibb** [comment]
Yes, they use fft() and ifft(). I think FFTW only has type 1 DCT and DST transforms though...

**Comment by dlfivefifty** [comment]
Oh OK, but these transforms are probably less important than type 1 and 2, so the extra factor of 2 is tolerable

**Comment by ajt60gaibb** [comment]
And there are things like DCT of type  3 is really a IDCT of type 2.  I forget all the interconnections.   Yeah, 8 of the transforms are truly exotic!
