### ISSUE TITLE
Is there a Chebyshev analogue to Estrin's scheme? 

### ISSUE THREAD

**Issue by ajt60gaibb** [ApproxFun/ApproxFun.jl#213]
We know that Clenshaw's algorithm is a degree-graded analogue of Horner's algorithm.  Is there a Chebyshev analogue of Estrin's scheme? 

https://en.wikipedia.org/wiki/Estrin's_scheme

This question has little to do with `ApproxFun.jl`, except that if there is an analogue then the algorithm may be useful for it.

**Comment by MikaelSlevinsky** [comment]
Estrin's scheme doesn't have the best [reputation](https://static.ph.ed.ac.uk/dissertations/hpc-msc/2009-2010/Gavin%20Reynolds.pdf). Even with a pre-allocated array, it's not faster than Horner's method, though maybe the way I wrote it SIMD didn't kick in.

```julia
julia> using ApproxFun

julia> const ret_estrin = Vector{Float64}(2^20);

julia> function estrin(c::AbstractVector{Float64},x::Float64)
           n = length(c)
           if isempty(c)
               return zero(Float64)
           end
           @assert ispow2(n)

           for k=1:n
               ret_estrin[k] = c[k]
           end
           nn = n >> 1
           while nn > 1
               @simd for k = 1:nn
                   k2 = 2k
                   @inbounds ret_estrin[k] = muladd(x,ret_estrin[k2],ret_estrin[k2-1])
               end
               x = x*x
               nn >>= 1
           end
           muladd(x,ret_estrin[2],ret_estrin[1])
       end
estrin (generic function with 1 method)

julia> c = rand(2^13).*exp(-0.005collect(1:2^13)); x = 1.0;

julia> @time for j=1:1000_000 ApproxFun.horner(c,x) end
 17.508116 seconds (1000.00 k allocations: 15.259 MB, 0.02% gc time)

julia> @time for j=1:1000_000 estrin(c,x) end
 17.908365 seconds (1000.00 k allocations: 15.259 MB, 0.02% gc time)

```

**Comment by MikaelSlevinsky** [comment]
Ok I added one more SIMD and it's a bit faster than Horner's method now.

**Comment by dlfivefifty** [comment]
I think this is less of an issue and more of a discussion, so is more appropriate for Julia-spectral group

**Comment by MikaelSlevinsky** [comment]
Will Estrin (and Chebyshev analogues) be more appropriate with the introduction of multi-threading in v0.5? The experiments conducted by G. Reynolds in his [M Sc thesis](https://static.ph.ed.ac.uk/dissertations/hpc-msc/2009-2010/Gavin%20Reynolds.pdf) are across multiple processors, while multi-threading on the same core could give the parallel schemes an edge.

**Comment by dlfivefifty** [comment]
I think threading in 0.5 is listed as experimental, so we may want to wait to 0.6 unless there's a pressing need
