### ISSUE TITLE
LowRankFun{PiecewiseSpace,...}

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#214]
ApproxFun's templated `LowRankFun` algorithm currently allows for construction on the `TensorSpace` of two `FunctionSpace`s. Surprisingly, this also allows for `LowRankFun`s on `TensorSpace`s of `PiecewiseSpace`s.

If it's forming the row and column slice that intersect at the maximum absolute value at a given step (that must be on only one of the subspaces unless there is some symmetry), is this simultaneous complete pivoting or something else?

```julia
using ApproxFun
d = Interval([-2,-1])∪Interval([1,2])
F = LowRankFun((x,y)->besselj0(abs(y-x)),Space(d),Space(d))
rank(F) # = 9 ≪ Sum of ranks of LowRankFuns on all 4 TensorSpaces!
```

**Comment by ajt60gaibb** [comment]
I do not understand what this means: "that must be on only one of the subspaces unless there is some symmetry".   

Sounds like standard complete pivoting to me... To me, the 1D spaces are an independent choice to the pivoting strategy.

**Comment by MikaelSlevinsky** [comment]
oh i just meant that the approximate absolute maximum at each iteration could only be on one of the four `TensorSpace`s [-2,-1]^2, [-2,-1]⊗[1,2], [1,2]⊗[-2,-1], [1,2]^2 in the example above. If there were symmetry, then there could be coincidence.

**Comment by MikaelSlevinsky** [comment]
Thanks I think that's cleared up for me now!

**Comment by ajt60gaibb** [comment]
Oh, I see.  To me, this is still GE with complete pivoting. If this was a partitioned matrix, then we would be certain. :)
