### ISSUE TITLE
Higher-order nonlinear BVPs

### ISSUE THREAD

**Issue by cmarcotte** [ApproxFun/ApproxFun.jl#225]
For example, the [Blasius function](http://www.chebfun.org/examples/ode-nonlin/Blasius.html) (and its generalization, Falkner-Skan), would make helpful examples to show off the capabilities (and limitations) of the package.

**Comment by cmarcotte** [comment]
I went ahead and implemented it. Can anyone help me to submit it for an example?

**Comment by dlfivefifty** [comment]
Sounds great, Christopher!  

The best way is to make a pull request.   The steps are roughly (1) Fork the repository (click Fork on ApproxFun’s github site), (2) checkout your Fork, (3) make your changes, (4) commit and push your changes to your fork and (5) create a pull request to have the changes merged back into ApproxFun.
