### ISSUE TITLE
Add operator preconditioners

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#248]
With #245, it should be possible to add operator preconditioners (described for linear ODEs in *Olver & Townsend 2013* and other preconditioners for singular integral operators in *Slevinsky & Olver 2015*) for operators of bandwidth zero, but not necessarily diagonal. Something like:
```julia
immutable Preconditioner{T,O} <: BandedOperator{T}
    op::O
    # b = bandinds(op).
    # inner constructor checks b[2] == b[1]
end

bandinds(P::Preconditioner) = bandinds(P.op)

function addentries!(P::Preconditioner,A,kr,:)
    addentries!(P.op,A,kr,:)
    A[:,:] = one(eltype(P))./A[:,:]
end

# These might be right under certain conditions.
domainspace(P::Preconditioner) = rangespace(P.op)
rangespace(P::Preconditioner) = domainspace(P.op)
```
This would accompany #199.

**Comment by dlfivefifty** [comment]
I'm not sure this belongs in ApproxFun itself, maybe a future ApproxFunIterativeSolvers.jl package?
