### ISSUE TITLE
Fix Fun(x->0)

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#250]
When it returns identically zero the constructor should converge but doesn't:

julia> Fun(x->0)
WARNING: Maximum length 1048577 reached
Fun([0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0  …  0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0,0.0,-0.0],Chebyshev(【-1.0,1.0】))

**Comment by MikaelSlevinsky** [comment]
This works for the `LowRankFun` constructor:
```julia
julia> LowRankFun((x,y)->0)
LowRankFun{Ultraspherical{0},Ultraspherical{0},TensorSpace{(Ultraspherical{0},Ultraspherical{0}),RealBasis,2},Float64,Float64}([Fun([0.0],Chebyshev(【-1.0,1.0】))],[Fun([0.0],Chebyshev(【-1.0,1.0】))],Chebyshev(【-1.0,1.0】)⊗Chebyshev(【-1.0,1.0】))
```

It's due to [this line](https://github.com/ApproxFun/ApproxFun.jl/blob/master/src/Multivariate/LowRankFun.jl#L83), which could be adapted.
