### ISSUE TITLE
Rename length(::Fun)

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#251]
This is confusing for vector-valued funs: one would expect

```julia
f=Fun(x->[exp(x),sin(x)])
length(f)
```

to be 2, but now its the number of coefficients. 

Maybe one of 

`ncoefficients(f)`
`coefficientslength(f)`
`ncoeffs(f)`
`numcoeffs(f)`

 is better?

**Comment by dlfivefifty** [comment]
It also causes problems with 

for fp in f
...

**Comment by dlfivefifty** [comment]
`length` is now `ncoefficients`

**Comment by MikaelSlevinsky** [comment]
What about `dof` as in degrees of freedom? We didn't give that one any thought originally, but it's a catchy alternative to `ncoefficients`.
