### ISSUE TITLE
in(0.0,Interval()) == false

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#269]
To save the hassle, this commit https://github.com/ApproxFun/ApproxFun.jl/commit/c91d24baadcd9ec7c86941d8a672a9b9add964f2 is the perpetrator, but I don't know what you are doing to make it work for Line. (BTW, this broke SIE).
```julia
    y=tocanonical(d,x)
```
has the wrong sign, and this line
```julia
    abs(imag(y))<100eps(T)/sc && -one(real(T))-100eps(T)/length(d)<ry<one(real(T))+100eps(T)/ry
```
appears inconsistent. (Why length(d) on one side and ry on the other?)

**Comment by dlfivefifty** [comment]
Whoops, that line was completely wrong: it should have been sc instead of both length(d) and ry.  This is to handle the case of Line() where length(d) is Infinite, so we use the local stretch for the tolerance.
