### ISSUE TITLE
Clarification question: ApproxFun not for fitting a curve to some data?

### ISSUE THREAD

**Issue by floswald** [ApproxFun/ApproxFun.jl#275]
Hi guys,

I just wanted to check whether I see this correctly or if it's that I'm missing something. With ApproxFun I can approximate *anything* that has an algebraic representation. However, I cannot take a sample of data (where I don't know the algebra that created it), and get a curve that fits this data well in some sense.

**Comment by dlfivefifty** [comment]
Hi Florian,

	It’s not built-in, but it is possible to work directly with data.  Here are some examples:

```julia
# Interpolate data on an evenly spaced grid with Fourier series

S=Fourier([0,2π])
x=points(S,20)
v=cos(cos(x))
f=Fun(ApproxFun.transform(S,v),S)


# Interpolate data on a Chebyshev grid with Chebyshev series

S=Chebyshev([0,1])
x=points(S,20)
v=cos(cos(x))
f=Fun(ApproxFun.transform(S,v),S)

# Least squares approximation of data on an evenly spaced grid with Chebyshev series

function vandermonde(S,n,x::AbstractVector)
    V=Array(Float64,length(x),n)
    for k=1:n
        V[:,k]=Fun([zeros(k-1);1],S)(x)
    end
    V
end


x=collect(0:0.001:1.)
S=Chebyshev([0.,1.])
V=vandermonde(S,20,x)
v=cos(cos(x))
f=Fun(V\v,S)
```

For the last case, make sure `length(x) >> n`.

**Comment by floswald** [comment]
great thanks!

**Comment by jarvist** [comment]
Hi Sheehan,

Unfortunately this code you very kindly provided appears to have stopped working!

I've re-written it as a minimal update (all of the Intervals() functions) to current ApproxFun, but it still stalls at the construction of the `V[:,k]` matrix elements. Mainly it seems that trying to evaluate the whole vector Fun(x) in that line stalls. Can you no longer evaluate Fun's for a whole 1xN array? I guess unrolling the loop by hand is possible, but seems a bit clunky for Julia!

```
# Interpolate data on an evenly spaced grid with Fourier series

S=Fourier(Interval(0,2π))
x=points(S,20)
v=cos(cos(x))
f=Fun(S,ApproxFun.transform(S,v))


# Interpolate data on a Chebyshev grid with Chebyshev series

S=Chebyshev(Interval(0,1))
x=points(S,20)
v=cos(cos(x))
f=Fun(S,ApproxFun.transform(S,v))

# Least squares approximation of data on an evenly spaced grid with Chebyshev series

function vandermonde(S,n,x::AbstractVector)
    V=Array(Float64,length(x),n)
    for k=1:n
        V[:,k]=Fun([zeros(k-1);1],S)(x)
    end
    V
end


x=collect(0:0.001:1.)
S=Chebyshev(Interval(0.,1.))
V=vandermonde(S,20,x)
v=cos(cos(x))
f=Fun(V\v,S)
```

Fails on (from latest version)
```
ERROR: LoadError: MethodError: no method matching isless(::Array{Float64,1}, ::Int64)
Stacktrace:  [1] in(::Array{Float64,1}, ::ApproxFun.Segment{Float64}) at /Users/jarvist/.julia/v0.7/ApproxFun/src/Fun/Domain.jl:116
```

That line being part of `Base.in(x,d::IntervalDomain)`,
```
    sc=norm(fromcanonicalD(d,ry<-1?-1:(ry>1?1:ry)))  # scale based on stretch of map on projection to interal
```
Trying to do some kind of map / scale, which assumes ry has a single value?

**Comment by dlfivefifty** [comment]
You need to now use broadcast notation to evaluate on a vector:
`Fun([zeros(k-1);1],S).(x)`

**Comment by jarvist** [comment]
Ah of course! Thank you very much. 

Here's a fully fixed up (no deprecation warnings) version of the above code with broadcasts.

```
# Interpolate data on an evenly spaced grid with Fourier series

S=Fourier(Interval(0,2π))
x=points(S,20)
v=cos.(cos.(x))
f=Fun(S,ApproxFun.transform(S,v))


# Interpolate data on a Chebyshev grid with Chebyshev series

S=Chebyshev(Interval(0,1))
x=points(S,20)
v=cos.(cos.(x))
f=Fun(S,ApproxFun.transform(S,v))

# Least squares approximation of data on an evenly spaced grid with Chebyshev series

function vandermonde(S,n,x::AbstractVector)
    V=Array{Float64}(length(x),n)
    for k=1:n
        V[:,k]=Fun(S,[zeros(k-1);1]).(x)
    end
    V
end


x=collect(0:0.001:1.)
S=Chebyshev(Interval(0.,1.))
V=vandermonde(S,20,x)
v=cos.(cos.(x))
f=Fun(S,V\v)
```

**Comment by dlfivefifty** [comment]
Great! I probably should have done a deprecation cycle, but unfortunately I have limited time.

**Comment by falematte** [comment]
Thanks for addressing this. I think this is a useful feature that should become built in
