### ISSUE TITLE
Installation on Windows 7 fails

### ISSUE THREAD

**Issue by portig** [ApproxFun/ApproxFun.jl#277]
Trying to install ApproxFun on my Windows 7 system under Julia 0.4.1 fails as follows:

julia> Pkg.add("ApproxFun")
INFO: Cloning cache of ApproxFun from git://github.com/ApproxFun/ApproxFun.jl.git
INFO: Cloning cache of FastGaussQuadrature from git://github.com/ajt60gaibb/FastGaussQuadrature.jl.git
INFO: Installing ApproxFun v0.0.8
error: unable to create file examples/Time Evolution PDEs on Disk (GLPlot) *broken*.ipynb (Invalid argument)
error: unable to create file examples/Time Evolution PDEs on Square (GLPlot) *broken*.ipynb (Invalid
argument)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

ERROR: failed process: Process(`git clone -q 'C:\Users\portig\.julia\v0.4\.cache\ApproxFun' ApproxFun`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:46
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

Other packages such as PyPlot, Dierckx and others install just fine. Any suggestions on how to proceed?
Thanks, Harald

**Comment by dlfivefifty** [comment]
I've removed the character "*" from the file names.  Can you try doing Pkg.checkout("ApproxFun") to see if that fixes the issue?

**Comment by portig** [comment]
This is what happened the first time I tried this:

julia> Pkg.checkout("ApproxFun")
ERROR: ApproxFun is not a git repo
 in checkout at pkg/entry.jl:203

After this I tried the 'Pkg.add("ApproxFun")' again, and it failed as before. I then removed ApproxFun and FastGaussionQuadrature from ~\.jula\.cache and tried both the 'checkout' and 'add' with various failures.

Then, finally after doing the removals from .cache again, the 'add' succeeded and I was able to do the example shown in the readme.md including the plot with the roots. There seems to be something flaky that makes the outcome of the installation process lead to different results at different times.

As a side note: I installed the package on a Mac without error messages and was able to do the first example in readme.md up through the plot of the curve, but the plot command for the roots failed. I am not at that machine right now, and I don't remember if there was an error message from the 'PyPlot.plot(r,h(r),"og",rp,h(rp),"or")' command

**Comment by dlfivefifty** [comment]
OK I need to tag a new version then, as you need to add it first.  In the meantime, you can try

		Pkg.clone("https://github.com/ApproxFun/ApproxFun.jl <https://github.com/ApproxFun/ApproxFun.jl>”)

**Comment by dlfivefifty** [comment]
I've tagged a new version, does Pkg.add("ApproxFun") work now?

**Comment by dlfivefifty** [comment]
I'm closing this as I assume its fixed now
