### ISSUE TITLE
Implement  erf(sqrt(Fun([0.,1.])))

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#278]
erf has an odd Taylor series at the origin so above can be represented with square root singularities.  I tried the ODE version from specialfunctions.jl:

```julia
f=sqrt(x)
D=Derivative(space(f))
[dirichlet(space(f));(f'*D^2+(2f*f'^2-f'')*D)]\[erf(f(0.)),erf(f(1.))]
```

To no avail.

**Comment by MikaelSlevinsky** [comment]
Regardless of the error message, is it still ill-posed? The left boundary condition is trivially satisfied by every function in the space.

**Comment by dlfivefifty** [comment]
Maybe it only needs 1 boundary condition?  If we precondition by integration doesn’t that reduce the order of the ODE to a first order?

**Comment by MikaelSlevinsky** [comment]
right, the second-order formulation avoids creating `exp(f^2)` first, but maybe a ``cumsum`` of that would be better, idk.

**Comment by dlfivefifty** [comment]
Not sure if this is the same as what you said, but I was thinking the following: if 

```julia
(f'*D^2+(2f*f'^2-f'')*D)*u = 0
u(0.) = erf(f(0.))
u(1.) = erf(f(1.))
```

Then define 
```julia
	u=cumsum(v) + erf(f(0.))
```
Plugging in gives us a first-order equation:

```julia
(f'*D+(2f*f'^2-f''))*v = 0
sum(v) = erf(f(1.))-erf(f(0.))
```

In other words, solve 
```julia
v=[DefiniteIntegral();(f'*D+(2f*f'^2-f''))] \ [erf(f(1.))-erf(f(0.))]
u=cumsum(v)+erf(f(0.))
```

This works for `f=Fun(exp,[0.,1.])` but not `sqrt(x)`

**Comment by MikaelSlevinsky** [comment]
what to do when `first(f) == last(f)` (or even when they're nearly equal, and how to quantify nearly)?

**Comment by dlfivefifty** [comment]
Good question!

**Comment by dlfivefifty** [comment]
This is fixed now!  The ODE solver was a bug Multiplication(::Fun{<:JacobiWeight},::JacobiWeight)

Note that it still solves with dirichlet, even though for JacobiWeight(0.5,0.), one of the functionals is [0 0 0 0...]
