### ISSUE TITLE
Add ETDRK4 fourth-order time-stepping for stiff PDEs

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#286]
The Kassam and Trefethen [classic](https://people.maths.ox.ac.uk/trefethen/publication/PDF/2005_111.pdf) uses a contour integral to stabilize coefficients in the scheme (Eq (2.5)), but I just added more efficient Taylor expansions near the numerical instability.

The Taylor expansions require about 18 coefficients in double precision, but the contour integral requires at least 32 calls to `exp` (and uses complex numbers), so this is unequivocally better.

Implementing the scheme should now be straightforward.

**Comment by MikaelSlevinsky** [comment]
I should add the caveat that the Taylor expansions would only be useful for diagonal operators in the linear part of the splitting u_t = Lu + N(u), while the contour method allows more general operators.

**Comment by dlfivefifty** [comment]
Similar to what I said in the other thread: why not use rational expansion of the exponential?  The issue with contour integrals is that you need to know where the spectrum of the operator is

**Comment by MikaelSlevinsky** [comment]
Sorry, perhaps the more pertinent issue to ApproxFun is that `rangespace(L) == domainspace(L)` so that it's sensible to define operator functions by their formal power series.

**Comment by dlfivefifty** [comment]
For Taylor series then yes

But Taylor series for exponential seems like a bad idea: exp(-x) has lots of cancellation for large x, and operators have infinite spectrum.  Only way to do Taylor series then is to restrict the stepsize based on length of solution.  This works..but is very much counter to approxfun mentality of doing things in inf dimensions

**Comment by dlfivefifty** [comment]
Plus applying an operator and inverting an operator are both O(n) operations, so it's not obvious Taylor series is faster (all about constant in front)

**Comment by MikaelSlevinsky** [comment]
Padé approximants are also defined for `f` satisfying a formal power series.

**Comment by MikaelSlevinsky** [comment]
Many of the important nonlinear PDEs have L diagonal anyways.

**Comment by dlfivefifty** [comment]
Only for periodic bcs, which are pretty boring.

**Comment by MikaelSlevinsky** [comment]
Looks like a scaling-and-squaring argument could be considered. Neat to know that all the Padé approximants are known for the phi functions (section 4.5 of [this thesis](http://www.diva-portal.org/smash/get/diva2:123208/FULLTEXT01.pdf)).

My original interest was in boring periodic boundary conditions, in which case the best and fastest way to stabilize the scheme (in my opinion and specifically in Julia where writing your own special functions is practical) is with sufficiently accurate Taylor series near the origin and the actual expression sufficiently far away. This is correct because element-wise == matrix-valued functions for diagonal matrices and operators.

Symplectic integrators may be more natural for integrable systems, but this would require solving nonlinear equations for `Funs`, ugh.

**Comment by MikaelSlevinsky** [comment]
Another approach would be generalized eigendecomposition for operators.

**Comment by dlfivefifty** [comment]
For self adjoint yes (the work with Marcus allows this).  For general differential operators with boundary conditions I'm not so sure...I suppose you could calculate the Schur decomposition which would reduce the problem to upper triangular operators.

**Comment by MikaelSlevinsky** [comment]
Probably operator exponentials are only practical for diagonal L. Otherwise, linear complexity in space is lost (and a simpler discretization or scheme should've been chosen).

**Comment by dlfivefifty** [comment]
I don't understand:  rational approximation and contour integration methods both still have linear complexity.

**Comment by MikaelSlevinsky** [comment]
you're right. EDIT: undo.

**Comment by MikaelSlevinsky** [comment]
There is an ETDRK4 method and two examples with periodic boundary conditions: Burgers' equation and Kuramoto-Sivashinsky equation.
