### ISSUE TITLE
document low-level constructors?

### ISSUE THREAD

**Issue by stevengj** [ApproxFun/ApproxFun.jl#296]
It would be nice to document some of the lower-level `Fun` constructors, to have more control over this process.

For example, a student of mine needs to manually decide on the number of Chebyshev points, get the set of abscissae, and possibly evaluate them manually into an array of values from which the `Fun` is constructed.   (e.g. each point may require a huge simulation, perhaps even by an external program like Comsol).  But we would still like to use ApproxFun so that we don't have to re-implement a bunch of basic functions for evaluation, differentiation, root-finding, etcetera.   I figured out how to do this by digging through the ApproxFun source code and [posted an explanatory notebook](http://nbviewer.jupyter.org/url/jdj.mit.edu/~stevenj/approxfun.ipynb), but in the long run it would be better if this were documented.

cc: @rpestourie

**Comment by dlfivefifty** [comment]
Yes ApproxFun needs a lot more documentation.  Thanks for putting this together.  Are you happy for me to copy your notebook into the wiki?  (There's a little rough documentation on Spaces in the wiki already.)

**Comment by dlfivefifty** [comment]
I also added a link to the ApproxFun Documentation Wiki

https://github.com/ApproxFun/ApproxFun.jl/wiki/ApproxFun-Documentation

to the README.

**Comment by stevengj** [comment]
Please feel free to copy whatever you want from my notebook.

**Comment by dlfivefifty** [comment]
OK it's copied into the documentation, thanks again!
