### ISSUE TITLE
Use Householder instead of Givens

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#300]
Householder should perform faster for large bandwidth problems.  We could also add Gaussian elimination for even faster still.

**Comment by dlfivefifty** [comment]
@ajt60gaibb you're off the hook: Marcus is doing this.  I'll try to find another issue to assign you 😜

**Comment by marcusdavidwebb** [comment]
Just implemented it. Tested it on some linear second order ODEs with high bandwidths. Don't know if faster yet. To use it, call householderadaptiveqr instead of adaptiveqr or backslash.

**Comment by MikaelSlevinsky** [comment]
Integral equations have large bandwidth if you want some model problems where Householder may be beneficial. Try the Helmholtz code with large wave number on SingularIntegralEquations readme.

This may help optimize: since the bandwidth is considered fixed (by bandinds), can the householderadaptiveqr method allocate w once and have the householderreduce methods work with this same vector rather than re-allocate for every zeroed-below-main-diagonal column?

**Comment by marcusdavidwebb** [comment]
Good advice on the allocate w once. Will do that.

**Comment by MikaelSlevinsky** [comment]
This is frustrating: all the remaining allocations come from slicing, but explicitly writing the loops doesn't beat level 1 BLAS + allocating `SubArray`s. Using Level 2 BLAS might be helpful, but all the base methods assume a `StridedArray` whereas ApproxFun's `BandedMatrix <: AbstractSparseMatrix`.

**Comment by MikaelSlevinsky** [comment]
A workaround is to define a *single mutable* `UnitStrideSubArray` for each of the `BandedMatrix`, `FillMatrix`, Householder vector and right-hand side. A `slice` in the current code would translate to simply changing the indices inside the type. With Level 1 BLAS overrides for `dot` and `axpy!`, it would be fast and allocation-free.

**Comment by MikaelSlevinsky** [comment]
Should a `BandedMatrix` use column-major ordering? This way the ordering of a banded matrix and its underlying dense data matrix are the same. Pointers referencing an element will then allow access to the columns (rather than the rows) stored contiguously in memory. This could improve performance of reflectors.

**Comment by dlfivefifty** [comment]
The reason I did this ordering is that add entries! populates row by row, and  givens rotations act on the rows one at a time.

But maybe add entries! should populate column by column, and householder used which acts on the columns.

 
We should probably include both versions of BandedMatrix now that the row version is  implemented.  We may also wish to create a separate package.

**Comment by dlfivefifty** [comment]
This is implemented in BandedMatrices.jl with timings below.  Need to move over to adaptive QR.  I think I'll revamp it by adding a `HouseholderOperator` so that one can do 
```julia
Q,R = qr([dirichlet();D^2-I])
```

And then the reflections of `Q` are populated dynamically.  



```julia
println("Large dimension QR solve")
A=brand(100000,100000,3,4)
b=rand(size(A,1))
@time Q,R=qr(A)
@time R\(Q'*b)

println("Time should be   0.030149 seconds (23 allocations: 17.548 MB)")
println("Time should be   0.008210 seconds (29 allocations: 8.012 MB)")


A=brand(2000,2000,400,400)
b=rand(size(A,1))
@time Q,R=qr(A)
@time R\(Q'*b)


println("Time should be   0.401671 seconds (24 allocations: 36.665 MB)")
println("Time should be   0.009276 seconds (30 allocations: 12.262 MB)")
```

**Comment by dlfivefifty** [comment]
This is beautiful,  the solve time is already much faster even the first time, and more so the second, and there's still a huge speed bug to fix:

```julia
S=Chebyshev()
A=[dirichlet(S);Derivative(S)^2 - I]
b=ones(10000)
@time A\b       # 0.018999 seconds
@time R\(Q'*b)  # 0.006588 seconds
@time R\(Q'*b)  # 0.000624 seconds
```

**Comment by dlfivefifty** [comment]
`A\b` is still the old Givens solve

**Comment by marcusdavidwebb** [comment]
Yes you need to use householderadaptiveqr directly.

**Comment by dlfivefifty** [comment]
I rewrote it in BLAS, see qrfact.jl

**Comment by marcusdavidwebb** [comment]
Wow. Hadn't been keeping up. Nice work.

**Comment by MikaelSlevinsky** [comment]
I can't wait to use this in the hierarchical solve.

**Comment by MikaelSlevinsky** [comment]
so both `Q` and `R` both store the same QROperator?

**Comment by dlfivefifty** [comment]
yes because they have to grow together adaptively

**Comment by dlfivefifty** [comment]
This is now implemented and Given's has been removed.
