### ISSUE TITLE
roots returns incorrect result for a simple "odd-looking" function

### ISSUE THREAD

**Issue by ikirill** [ApproxFun/ApproxFun.jl#303]
The following two series differ by about `1e-16`, but the root returned for the first function is no where near any actual root. In fact, if you plot the first function with ApproxFun.plot, it is clear it does not have any roots at all near 0.5.

```
julia> roots(Fun([0.61394304729989,0.0,-1.0,0.0,-0.0018460972984156861,-4e-16], Chebyshev([0.0,1])))
1-element Array{Float64,1}:
 0.433247

julia> roots(Fun([0.61394304729989,0.0,-1.0,0.0,-0.0018460972984156861,-3e-16], Chebyshev([0.0,1])))
2-element Array{Float64,1}:
 0.0507791
 0.949221 
```

The functions are "strange", having such tiny last coefficient, but I think this can be considered a failure of roots. That said, I'm not really sure what guarantees it's supposed to make, but perhaps still a bug?

The value of the "bad" function at the "root" is `1.57671`, the values of the "good" function at its roots are `-4.44e-15/-4.44e-16`, so it's not even close.

I did `Pkg.checkout("ApproxFun")` before trying this, and here is `versioninfo()`:
```

julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

**Comment by ikirill** [comment]
Another funky example, I don't know why it does this:
```

julia> [roots(Fun([0.61394304729989,0.0,-1.0,0.0,-0.0018460972984156861,k * (-1e-16)], Chebyshev([0.0,1]))) for k=1:16]
16-element Array{Any,1}:
 [0.050779089890322815,0.9492209101096767]
 [0.050779089890322815,0.9492209101096767]
 [0.050779089890322815,0.9492209101096767]
 [0.43324656780049975]
 [0.4657502455467484]
 [0.496174609603527]
 [0.5926294205318297]
 [0.5135635983579055]
 [0.6705468753375479]
 [0.11162187905297322,0.8237124398336053]
 [0.20969849900909565,0.9305891800709365]
 [0.7087895682419858]
 [0.6807445546424914]
 [0.16786515767409232,0.8764330120567806]
 [0.07919399953177342,0.795370119604327]
 [0.18863782440611382,0.9018647861419606]
```

**Comment by dlfivefifty** [comment]
This was caused by  #135.  I've changed roots to call eigvals instead of hesseneigvals for now, which means it will be lower.

**Comment by ikirill** [comment]
Thank you, I didn't expect the eigensolver to fail like that.
