### ISSUE TITLE
Eigenvalue

### ISSUE THREAD

**Issue by rveltz** [ApproxFun/ApproxFun.jl#306]
Hi,

It seems eigenvalues are not possible yet within the package. Do you intend to add it?

Thank you,

Best

**Comment by MikaelSlevinsky** [comment]
I think we do have two overrides of `eigvals` [here](https://github.com/ApproxFun/ApproxFun.jl/blob/development/src/Extras/eigs.jl). They don't automatically deflate eigenvalues of the operator, though, and there's no guarantee on the results. Something like
```julia
d = Interval()
eigvals([dirichlet(d);-Derivative(d)^2],200)
```
should work, but I can check at work later today if it doesn't.

**Comment by dlfivefifty** [comment]
I can add an “eig” command that also returns approximate eigenvectors

**Comment by rveltz** [comment]
Thank you, it works. Adding approximate eigenvectors and specify which eigenvalues (rightmost,...) would be  a plus.
Best,

**Comment by rveltz** [comment]
I am almost done...

Basically, I want to be able to look at the eigenvalues of 
Lu(x) = -u(x)' - f(x) * u(x) - int( g*u )
But I have troubles to implement the int part. I hope this falls in the realm of your library.

Thank you,

Best

**Comment by MikaelSlevinsky** [comment]
Can you be a little more specific about `int`? Is it (in)definite integration, or a mixture like a Volterra operator?

**Comment by rveltz** [comment]
Sorry... I mean the integral over the domain d = Interval()

**Comment by MikaelSlevinsky** [comment]
and g is univariate or bivariate?

**Comment by rveltz** [comment]
Univariate.

For terms like `g1(x) int(g2 u)` or terms more general, a Fredholm operator would do the job but I am not sure it is implemented yet. 

This is also related to the question of how to define L in order to apply eigval to it. It seems an anonymous function would not work (?)

**Comment by MikaelSlevinsky** [comment]
Partial solution in gitter https://gitter.im/ApproxFun/ApproxFun.jl
