### ISSUE TITLE
DefiniteIntegral Error

### ISSUE THREAD

**Issue by rveltz** [ApproxFun/ApproxFun.jl#314]
Hi,

When using the following code
`using ApproxFun` 
`d = Interval(0.0,1.)`
`Φ = Fun(x->x.^2,d)`
`B = DefiniteIntegral()[Φ]`

I get the  error:

**TimesFunctional:ApproxFun.UnsetSpace()↦ConstantSpace
Error showing value of type ApproxFun.TimesFunctional{Float64,ApproxFun.DefiniteIntegral{ApproxFun.UnsetSpace,Float64},ApproxFun.ConcreteMultiplication{ApproxFun.Ultraspherical{0,ApproxFun.Interval{Float64}},ApproxFun.UnsetSpace,Float64,Float64}}:
ERROR: No range space attached to Multiplication
 in getindex at /Users/rveltz/.julia/v0.4/ApproxFun/src/Operators/banded/algebra.jl:217
 in show at /Users/rveltz/.julia/v0.4/ApproxFun/src/Extras/show.jl:208
 in anonymous at show.jl:1299
 in with_output_limit at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in showlimited at show.jl:1298
 in writemime at replutil.jl:4
 in display at REPL.jl:114
 in display at REPL.jl:117
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:163
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_frontend at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_repl at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib**

**Comment by dlfivefifty** [comment]
This is fixed
