### ISSUE TITLE
LoadError: AbstractBandedMatrix not defined

### ISSUE THREAD

**Issue by adrogoul** [ApproxFun/ApproxFun.jl#323]
Hello,
I use ApproxFun, and after doing a check out of Approxfun, I got the  error displayed at the end of this message.
 Before today all was right for me.
Many thanks for your help,
Best 
Audric

julia> using ApproxFun
INFO: Precompiling module ApproxFun...
WARNING: could not import BandedMatrices.bandshift into ApproxFun
WARNING: could not import BandedMatrices.bandwidth into ApproxFun
WARNING: could not import BandedMatrices.AbstractBandedMatrix into ApproxFun
ERROR: LoadError: LoadError: LoadError: UndefVarError: AbstractBandedMatrix not defined
 [inlined code] from none:2
 in anonymous at no file:0
while loading /user/adrogoul/home/.julia/v0.4/ApproxFun/src/Operators/SubMatrix.jl, in expression starting on line 9
while loading /user/adrogoul/home/.julia/v0.4/ApproxFun/src/Operators/Operator.jl, in expression starting on line 99
while loading /user/adrogoul/home/.julia/v0.4/ApproxFun/src/ApproxFun.jl, in expression starting on line 31
ERROR: Failed to precompile ApproxFun to /user/adrogoul/home/.julia/lib/v0.4/ApproxFun.ji
 in compilecache at loading.jl:400
 in compilecache at loading.jl:389
 in require at loading.jl:266
 [inlined code] from /user/adrogoul/home/.julia/v0.4/Requires/src/require.jl:11
 in require at /user/adrogoul/home/.julia/v0.4/Requires/src/hook.jl:17

**Comment by dlfivefifty** [comment]
If you are on the development branch, then you need to be on the master branch of BandedMatrices. 

Though I recommend sticking to the tagged releases or master branch: the development branch is not intended for users

**Comment by adrogoul** [comment]
Ok, but I want to use the function Volterra which seems to be only on the developement branch. 
Can I get it differentely?
Best
Audric

**Comment by dlfivefifty** [comment]
I guess stay on development until we tag a new version

( the last push temporary slowed ODE solving down so a tag won't come until this is fixed)
