### ISSUE TITLE
RFC: JacobiWeight and Jacobi parameters are opposite

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/ApproxFun.jl#327]
I would prefer using the Jacobi polynomial convention that matches DLMF, even though the alpha and beta parameters are right-to-left rather than left-to-right singularities. One option would be to define beta first in the type.

**Comment by dlfivefifty** [comment]
Ok, and should the order also be swapped to be Jacobi(a,b)?

**Comment by MikaelSlevinsky** [comment]
Thanks!
