### ISSUE TITLE
Change plotting methods to use recipes

### ISSUE THREAD

**Issue by tbreloff** [ApproxFun/ApproxFun.jl#334]
See: https://github.com/tbreloff/Plots.jl/issues/311 and http://plots.readthedocs.io/en/latest/plots_v0.7/

Lets talk through what you need and I can help with converting.

**Comment by dlfivefifty** [comment]
This is implemented now in development, but I couldn't figure out to make different @series items all have the same colour.   How is this done?

**Comment by tbreloff** [comment]
If you know the color, you can just set it before (outside of) the series
macros and they'll all get it. If you want them all to be automatically
given the same color, then the first should get 'primary := true' and the
rest 'primary := false' which you could do in a loop as 'primary := (i ==
1)'

The primary/secondary just means they'll all be given the same series
index, which is what determines the color choice.

**Comment by dlfivefifty** [comment]
Great, it worked!
