### ISSUE TITLE
Wrap ODE time-stepping routines

### ISSUE THREAD

**Issue by anriseth** [ApproxFun/ApproxFun.jl#335]
I'm trying to solve an ODE on [0,T] with terminal value u(T) = -\alpha, of the form:
u' = -u^2/(2-\gamma^2*u)

The solution I get is wrong. I've added a comparison with Chebfun to show what I'm trying to do. The top plot is from chebfun, the lower one is from ApproxFun. Inspecting the ODE shows that the ApproxFun solution is clearly wrong (u is supposed to be decreasing when it is negative).
![chebfun_sol](https://cloud.githubusercontent.com/assets/5601805/15939073/1602796c-2e6e-11e6-8229-ca12305be39c.png)
![julia_sol](https://cloud.githubusercontent.com/assets/5601805/15939292/edb79702-2e6e-11e6-8db9-6f3e20d29998.png)

MATLAB code:
```matlab
T = 2; alpha = 3; gamma = 0.1;

dom = [0 T];
N = chebop(@(t,u) diff(u)+u.^2./(2-gamma.^2.*u), dom);
rhs = 0;
N.rbc = @(u) u+alpha;

u = N\rhs;
```

Julia code:
```julia
T = 2.; α = 3; γ = 0.1

x = Fun(identity,[0.,T])
d = domain(x)
D = Derivative(d)
B = rdirichlet(d)
N = D+I^2./(2-γ^2*I)

A = [B; N]
b = -α

u = A\b
```

**Comment by MikaelSlevinsky** [comment]
Hi Asbjørn,

since your problem is nonlinear in `u`, you will need to specify the operator as an anonymous function and use the `newton` solver with a reasonably accurate initial guess. The approach for nonlinear ODEs is outlined [here](https://github.com/ApproxFun/ApproxFun.jl#nonlinear-boundary-value-problems) for a BVP.

**Comment by anriseth** [comment]
Okay. Is there a plan to implement time-steppers for nonlinear IVPs? Chebfun did this in 5.1, and they claim it works better than the global methods.

http://www.chebfun.org/docs/guide/guide10.html#102-initial-value-problems-and-solveivp

**Comment by dlfivefifty** [comment]
I could see the case for the following override:

u=ode45((t,u)->-u^2/(2-γ^2*u),Interval(0.,2.))

**Comment by MikaelSlevinsky** [comment]
This provides very crude overrides to the methods from the ODE.jl package. A better solution would be to use the output from these overrides as initial guesses for Newton iteration. As can be seen at the end, the norm of the residual is nowhere near the set relative tolerance.
```julia
using ApproxFun, ODE, Plots

import ODE: ode23, ode45, ode78, ode4, ode4ms, ode23s, ode4s

for ode in (:ode23, :ode45, :ode78, :ode4, :ode4ms, :ode23s, :ode4s)
    @eval function $ode(fn, t0, y0, d::Space; reltol=eps(), kwargs...)
        t0added=false
        for logn = 4:20
            t = points(d, 2^logn)
            t0 ∉ t && (unshift!(t,t0); t0added=true)
            t, u = $ode(fn, y0, t; points=:specified, reltol=reltol, kwargs...)
            cf = t0added ? Fun(ApproxFun.transform(d,u[2:end]), d) : Fun(ApproxFun.transform(d,u), d)

            maxabsc=maxabs(cf.coefficients)
            if maxabsc==0 && maxabsfr==0
                return(zeros(d))
            end
            
            if length(cf) > 8 && maxabs(cf.coefficients[end-8:end]) < reltol
                return chop!(cf,reltol/10)
            end
        end
        warn("Maximum length "*string(2^20+1)*" reached")

        t = points(d, 2^21)
        t0 ∉ t && (unshift!(t,t0); t0added=true)
        t, u = $ode(fn, y0, t; points=:specified, kwargs...)

        t0added ? Fun(ApproxFun.transform(d,u[2:end]), d) : Fun(ApproxFun.transform(d,u), d)
    end
end

sp = Chebyshev(Interval(2,0))

u = ode45((t,u)->-u^2/(2-.1^2*u),2.0,-3.0,sp;reltol=eps(),abstol=realmin())

pyplot()

plot(u)

norm(u'+u^2/(2-.1^2*u))
```

**Comment by MikaelSlevinsky** [comment]
Newton iteration (using the most recent commit) gives essentially machine precision. Code updated above.

**Comment by anriseth** [comment]
That works well (and gives a higher precision than the Chebfun defaults),
thank you both.

I'll let you close the issue, in case you want to keep it open for
implementing ODE-overrides.

**Comment by dlfivefifty** [comment]
How about we put these into a new repository, ApproxFun/ApproxFunODE.jl, for the time being?  We can also consider wrapping:

https://github.com/luchr/ODEInterface.jl

**Comment by dlfivefifty** [comment]
I've created 

https://github.com/ApproxFun/SpectralTimeStepping.jl

which right now contains just an Example.  At some point I'll move the BDF codes over there.
