### ISSUE TITLE
bandindMethodError: `bandinds` has no method matching ...

### ISSUE THREAD

**Issue by adrogoul** [ApproxFun/ApproxFun.jl#336]
Hi,

I have trouble implementing a eigenvalue problem: 
I run the following code by loading ApproxFun:

F = x->x.^8
d = Interval(0.0,10.)
f = Fun(F,d)
ginf = @time Fun(x->exp(-x),d)
gp = @time ginf'
Af = @time Fun(x->x+f(x),d)
transport_ = Fun(x-> x - 1,d)
damping    = Fun(x-> 1 - f(x),d)
A  = @time transport_ *Derivative(d) + damping
P  = @time -DefiniteIntegral(Chebyshev(d))[LowRankFun((x,y)->gp(x)*(y+f(y)),d^2)];
λ,V = @time ApproxFun.eigs([A],20)
λ,V = @time ApproxFun.eigs([A+P],20)**# does not work : error : bandinds. It seems that the operator  A[end][1:n-nf,1:n] is not defined for low rank operators in this version of approxfun (ApproxFun 0.1.0+ master)**

I get the error : 
ERROR: MethodError: `bandinds` has no method matching bandinds(::ApproxFun.LowRankPertOperator{ApproxFun.PlusOperator{Float64},ApproxFun.LowRankOperator{ApproxFun.Ultraspherical{1,ApproxFun.Interval{Float64}},Float64},Float64})

It was working few months ago (may be I was on a  development branch I don't remember), but I don't remember which version of ApproxFun was working well.

Thanks for your help.

Audric

**Comment by adrogoul** [comment]
Hi,
the problem seems to come from the lowrankFun operator defined by :
LowRankFun((x,y)->gp(x)(y+f(y)),d^2)
Is there someone who know how to define this kind of operator without using this LowRankFun function or something which enables to convert this kind of LowRankFun operator in another type handled by the eigs function?
Thanks

**Comment by dlfivefifty** [comment]
Is that suppose to be `transport_*Derivative(d) + damping`?

**Comment by dlfivefifty** [comment]
And `>gp(x)*(y+f(y))`?

**Comment by adrogoul** [comment]
Yes, it was missing a *  symbol in my last message but my code was good, sorry.
The problem is at the line : 
λ,V = @time ApproxFun.eigs([A+P],20)
without adding P it works (λ,V = @time ApproxFun.eigs([A],20) works) but when I add the operator P which has been created with the LowRankFun function, ApproxFun.eigs raises an error.

**Comment by dlfivefifty** [comment]
This is fixed now

**Comment by dlfivefifty** [comment]
On "development" branch
