### ISSUE TITLE
RFC: Remove BandedOperator/Functional in favour of isfunctional/isbanded

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#340]
Moving to PDEs there will be more types of operators and it will be beneficial to restructure operators in a more a general fashion.  For example, we would want `PlusOperator` to be able to be used for both `BandedOperator` and `BandedBelowOperator`.  

I have two possible solutions: 

1.  Remove abstract `Operator` subtypes `BandedOperator`, `BandedBelowOperator`, `Functional`, etc. in favour of `isbanded`, `isbandedbelow`, etc.   Dispatching between the cases would no longer be possible by types, but a quick scan of the code suggests this is not a serious issue.

2. Do the following:
```julia
@enum Banded,BandedBelow,AlmostBanded,Row
abstract Operator{Struct,T}
typealias BandedBelowOperator{T} Union{Operator{Banded,T},Operator{BandedBelow,T},Operator{AlmostBanded,T}}
typealias BandedOperator{T} Operator{Banded,T}
```
This would allow dispatch, but seems like a non-standard idiom.

I'm leaning towards (1) as it simplifies the type infrastructure, but will have to think of whether depending on dispatch is essential to the design.

**Comment by dlfivefifty** [comment]
I started implementing (1) in branch feat-removespecialops.  I've successfully removed `Functional` (passing tests up to VectorTest).  I think simplifying the type hierarchy has a lot of benefits, and then we will be able to have, say, dense Conversion operators, Conversion(Chebyshev(),Legendre()), or rectangular Conversion operators, Conversion(ConstantSpace(),Chebyshev()).

**Comment by MikaelSlevinsky** [comment]
I suppose for logical completeness there could be support of operators with the following bandwidths and sizes:

isbanded => (a,b)
isbandedbelow => (c,Inf)
isbandedabove => (Inf,d)
else (Inf,Inf)

isafunctional/isarow => size( ,1) == 1
isacolumn => size( ,2) == 1

**Comment by dlfivefifty** [comment]
I'm planning to support any sizes.  So Functional will be a redundant concept, since in most cases you want to support any m x inf operators.

**Comment by dlfivefifty** [comment]
E.g. Dirichlet will become a 2 x inf operator from Chebyshev to PointSpace([-1,1]).  This will then mirror the PDE case.

The correct notation for the RHS will be (in 0.5)

[[2,3],f]

**Comment by dlfivefifty** [comment]
I do like the idea of all operators having bandwidth overrides, and isbanded is true in the case both are finite.

Then there can be a notion of "kronbandwidth" for PDEs.  I'm thinking in practice the best data structure in the first instance is still just a banded matrix, where the bandwidth is adaptively resized.

**Comment by dlfivefifty** [comment]
This will also allow removal of `FunctionalOperator`, as we will just have `Conversion(ConstantSpace(),Chebyshev())` which is an ∞ x 1 operator.

**Comment by dlfivefifty** [comment]
feat-removespecialops now passes all tests with `Functional` removed.  It was 100x easier than I thought it would be, and makes me excited to remove `PlusFunctional`, `FunctionalOperator`, `ConstantTimesFunctional`, .... with the next stage of remove `BandedOperator`!

See you next week

**Comment by dlfivefifty** [comment]
This is merged now
