### ISSUE TITLE
Fix sum(Fun(1,CosSpace())) == π

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#351]
Should be 2π.  The culprit is PiecewiseSpace, but fixing this needs some thought about SumSpace with different domains.

**Comment by MikaelSlevinsky** [comment]
All definite integrals should work: `sum(Fun([1],SinSpace()))` is also broken.

**Comment by dlfivefifty** [comment]
sum(Fun([1],SinSpace())) is fixed in the feat-revampbivariateops branch, which will hopefully be merged back soon

**Comment by dlfivefifty** [comment]
This was fixed...not sure when.
