### ISSUE TITLE
Avoid exposing vector of coefficients routines

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#376]
Right now the following interprets the RHS as coefficients:

``` julia
A = MyOperator()
A\[1.,2.]
```

But in some cases `rangespace(A)` is a `VectorSpace`, and so `[1.,2.]` would be more accurately interpreted as the Vector `[1.,2.]`, which would then be converted to a `Fun` in `rangespace(A)`, with not necessarily the coefficients `[1.,2.]`.  

I think the notion of coefficients should always be hidden, so the code above should always be the Vector `[1.,2.]`, throwing an error if necessary.  A side effect is the following:

``` julia
B=dirichlet()
L=D^2+I
A=[B;L]

A \ [1.,2.]  # currently allowed, but would give an error under the change as rangespace(A) doesn't contain 2d vectors
A \ [1.,2.,0.]  # would work, as the vector can be converted to the rangespace(A), which is TupleSpace((ConstantSpace(),ConstantSpace(),Chebyshev())
```

**Comment by MikaelSlevinsky** [comment]
In your example, one might consider promoting `[1.,2.]` to the `rangespace(A) = TupleSpace((ConstantSpace(),ConstantSpace(),Chebyshev())` thus creating an empty `Fun{Chebyshev}`. Is that the idea?

**Comment by MikaelSlevinsky** [comment]
Oh, no it should promote to a `Fun{TupleSpace}`. Abort.

**Comment by dlfivefifty** [comment]
It should promote to a `Fun{TupleSpace{Tuple{ConstantSpace,ConstantSpace}}}` (or `Fun{ArraySpace{ConstantSpace}}`, though I'm also thinking of combining ArraySpace and TupleSpace as they serve identical functions, just one assumes all spaces are the same.)  

Now whether a `Fun{TupleSpace{Tuple{ConstantSpace,ConstantSpace}}}` should be convertible to a `Fun{TupleSpace{Tuple{ConstantSpace,ConstantSpace,Chebyshev}}}` is debatable.  I think not, as requiring the extra `0.` makes the code a bit more explicit.  

Though after 0.4 is no longer supported, the actual code will be

```julia
B=Dirichlet()
L=D^2+I
A=[B;L]

A\[[1.,2.],0.]
```
which I think is much more explicit.  Then `rangespace(A)` will be `TupleSpace{Tuple{TupleSpace{Tuple{ConstantSpace,ConstantSpace}},Chebyshev}}`.

**Comment by dlfivefifty** [comment]
Fixed!
