### ISSUE TITLE
CachedOperators should inherit raggedness/etc

### ISSUE THREAD

**Issue by johnwormell** [ApproxFun/ApproxFun.jl#388]
I think this should be the case? I assume it happens naturally with isbandedbelow/above as that's done through bandinds, but doesn't happen for israggedbelow, and maybe not for the others.

**Comment by dlfivefifty** [comment]
Fixed!  I added a macro @wrapperstructure for operators that have the same structure of another operator (e.g., c*op, real(op) and cache(op)) so the overrides should be consistent in all cases now.
