### ISSUE TITLE
Add spacetest to run a suite of tests on a space

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#394]
I just added  `…operatortest` routines that run a suite of tests on an operator, which of course found a number of a bugs.

There should similarly be a `spacetest` that runs a suite of tests: e.g.,

```julia
function spacetest(S)
   f=Fun(rand(10),S)
   @test sum(f) DefiniteIntegral()*f
end
```

**Comment by MikaelSlevinsky** [comment]
Should these be macros? @spacetest @domaintest @operatortest

Cheers,

Mikael

On Oct 17, 2016, at 12:16 AM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


I just added ...operatortest routines that run a suite of tests on an operator, which of course found a number of a bugs.

There should similarly be a spacetest that runs a suite of tests: e.g.,

function spacetest(S)
   f=Fun(rand(10),S)
   @test sum(f) DefiniteIntegral()*f
end

-

**Comment by dlfivefifty** [comment]
They don't need to be yet, since they take in an operator, not an expression that creates an operator.

Though it would look nicer with an @

**Comment by dlfivefifty** [comment]
Done!  I renamed everything `test*` instead of `*test` for some reason.  

This has highlighted several bugs, some of which have been fixed.  As more spaces are tested, the limits of each space will be documented in the tests.  For example:

```julia
testspace(A)  # calculus and transform tests
testspace(A;minpoints=2)  # transform requires at least 2 sample points
testspace(A;invertibletransform=false)  # The transform is not invertible.  This may be due to a bug where the lengths are different
testspace(A;haslineintegral=false) # DefiniteLineIntegral or linesum not yet implemented
testtransforms(A)  # only test the transforms, not the calculus operations
testcalculus(A)  # only test calculus, not transforms
```
