### ISSUE TITLE
+ for Infinity{Bool}

### ISSUE THREAD

**Issue by marcusdavidwebb** [ApproxFun/ApproxFun.jl#397]
If I type 

Fun(x->x^2,Fourier())

I get the error "+ not defined for ApproxFun.Infinity{Bool}".

This seems strange to me, as +{B}(x::Infinity{B},y::Infinity{B}) is clearly defined in LinearAlgebra/helper.jl. Anyone else get this error? Happens in both master and development branches.

**Comment by MikaelSlevinsky** [comment]
Strange. I get this:
```julia
julia> using ApproxFun

julia> Fun(x->x^2,Fourier())
WARNING: Maximum number of coefficients 1048577 reached in constructing Fun.
Fun([3.28987,-8.0871e-18,-4.0,6.11664e-19,1.0,2.19456e-17,-0.444444,-5.82415e-19,0.25,8.45537e-18  …  -8.97635e-12,-6.38186e-20,8.97635e-12,6.50098e-20,-8.97638e-12,1.91906e-19,8.97626e-12,-1.23349e-20,-8.97638e-12,4.48819e-12],Fourier(【-3.141592653589793,3.141592653589793❫))

julia> Fun(x->x^2,Fourier(Circle()))
Fun(Complex{Float64}[0.0+1.53081e-17im,0.0+7.12802e-17im,7.85046e-17-3.06162e-17im,-0.0+1.0im,1.0+3.06162e-17im],Fourier(🕒))

```

**Comment by marcusdavidwebb** [comment]
Perhaps x->x^2 is a bad example to consider on Fourier()... but the same happens for me as above with functions like x->cos(sin(x)).

**Comment by marcusdavidwebb** [comment]
The + function on Infinity{Bool} is purely for checking the dimensions of the spaces it appears, but it appears to miss the definition which clearly exists in LinearAlgebra/helper.jl.

**Comment by dlfivefifty** [comment]
It probably means +(x::Infinity) which is missing, and should return x

**Comment by marcusdavidwebb** [comment]
Nope, because the following throws the same error:

x = ApproxFun.Infinity(false)
y = ApproxFun.Infinity(false)
x+y

However, x*y does not.

**Comment by dlfivefifty** [comment]
What's your version info?  It works for me in both 0.5 and 0.4.6 on the development branch.

**Comment by dlfivefifty** [comment]
as does +(x)

**Comment by marcusdavidwebb** [comment]
It throws the error in development branch for me. Now I'm using 0.3.3+ master branch and it still throws the error. Will change back to most recent on development to check.

**Comment by marcusdavidwebb** [comment]
Yep, still throws the error for x+y in development branch.

**Comment by marcusdavidwebb** [comment]
Oh, and the Julia version is 0.5.0

**Comment by dlfivefifty** [comment]
Can you call `versioninfo()` and `Pkg.status()` and copy the results.  Also, copy the full error.

**Comment by dlfivefifty** [comment]
It sounds like you tried to override + and ignored the "Warning: import Base.+ to override" message.  

Try Base.+ and see if that's better.

**Comment by marcusdavidwebb** [comment]
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

12 required packages:
 - AMVW                          0.0.0-             master (unregistered, dirty)
 - ApproxFun                     0.3.2+             development
 - Atom                          0.5.4
 - DifferentialEquations         0.4.2+             master
 - GR                            0.15.0
 - Gallium                       0.0.4
 - IJulia                        1.3.2
 - ImageView                     0.2.0
 - Interact                      0.3.5
 - JSON                          0.8.0
 - PyPlot                        2.2.4
 - QuartzImageIO                 0.1.4
91 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.4.0
 - BandedMatrices                0.1.1
 - BinDeps                       0.4.5
 - Blink                         0.4.3
 - COFF                          0.0.2
 - CRC                           1.2.0
 - Cairo                         0.2.35
 - Calculus                      0.1.15
 - ChunkedArrays                 0.1.0
 - CodeTools                     0.4.2
 - Codecs                        0.2.0
 - ColorTypes                    0.2.12
 - ColorVectorSpace              0.1.11
 - Colors                        0.6.9
 - Compat                        0.9.2
 - ComplexPhasePortrait          0.0.0-             master (unregistered)
 - Conda                         0.3.2
 - DWARF                         0.1.0
 - DataStructures                0.4.6
 - Dates                         0.4.4
 - Distances                     0.3.2
 - DualNumbers                   0.2.2
 - ELF                           0.1.0
 - EllipsisNotation              0.0.2
 - FastGaussQuadrature           0.1.0
 - FastTransforms                0.0.6
 - FileIO                        0.2.0
 - FixedPointNumbers             0.2.1
 - FixedSizeArrays               0.2.4
 - ForwardDiff                   0.2.5
 - GenericSVD                    0.0.2
 - Graphics                      0.1.3
 - Hiccup                        0.0.3
 - Homebrew                      0.4.0
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - Images                        0.5.14
 - IniFile                       0.2.5
 - InplaceOps                    0.0.5
 - IsospectralFlows              0.0.0-             master (unregistered, dirty)
 - IterativeSolvers              0.2.2
 - Iterators                     0.2.0
 - JuliaParser                   0.7.4
 - Juno                          0.2.3
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.4
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.3
 - Mustache                      0.1.2
 - Mux                           0.2.2
 - NLsolve                       0.7.3
 - NaNMath                       0.2.1
 - Nettle                        0.2.4
 - Notebooks                     0.0.0-             non-repo (unregistered)
 - ObjFileBase                   0.0.4
 - Optim                         0.6.1
 - Parameters                    0.5.0
 - PlotUtils                     0.1.1
 - Plots                         0.9.4
 - Polynomials                   0.1.0+             master
 - PositiveFactorizations        0.0.2
 - PyCall                        1.7.2
 - Ranges                        0.0.1
 - Reactive                      0.3.6
 - RecipesBase                   0.1.0
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - SIUnits                       0.1.0
 - Showoff                       0.0.7
 - SpectralMeasures              0.0.0-             master (unregistered)
 - StatsBase                     0.11.1
 - StructIO                      0.0.2
 - Sundials                      0.3.0
 - TerminalUI                    0.0.2
 - TexExtensions                 0.0.3
 - TextWrap                      0.1.6
 - Tk                            0.4.0
 - ToeplitzMatrices              0.1.1
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WebSockets                    0.2.1
 - Winston                       0.12.1
 - ZMQ                           0.4.0
 - Zlib                          0.1.12

`using ApproxFun
x = ApproxFun.Infinity(false)
y = ApproxFun.Infinity(false)
x+y # returns "+ not defined for ApproxFun.Infinity{Bool}"

using Base
import Base.+
Base.+(x,y) # returns "MethodError: no method matching .+(::Module, ::Tuple{ApproxFun.Infinity{Bool},ApproxFun.Infinity{Bool}})"`

Didn't get any warning about importing Base.+.

**Comment by dlfivefifty** [comment]
That's bizarre....I'm assuming you've tried `Pkg.update()`?  There was a bad commit to ApproxFun yesterday (6cbdad8ef37fd3921893466cc86cb2ca2581c6f6).  Maybe wipe your .julia/v0.5 folder and add ApproxFun from scratch?

**Comment by marcusdavidwebb** [comment]
Yes everything is up to date (except AMVW, but that is irrelevant here).

**Comment by marcusdavidwebb** [comment]
More verbose error says:
ERROR: + not defined for ApproxFun.Infinity{Bool}
 in +(::ApproxFun.Infinity{Bool}, ::ApproxFun.Infinity{Bool}) at ./promotion.jl:255

**Comment by dlfivefifty** [comment]
Try deleting .julia/lib as maybe there were warnings when it precompiled the packages.

Also, see if ApproxFun.+ works

**Comment by marcusdavidwebb** [comment]
ApproxFun.+(x,y) throws the same error. I'll try deleting .julia/lib

**Comment by marcusdavidwebb** [comment]
Deleted .julia/lib. It precompiled ApproxFun when I called using ApproxFun. x+y still  threw the same error.

**Comment by dlfivefifty** [comment]
I added some tests for Infinity(false) + Infinity(false), so you can verify that I'm not lying:

https://travis-ci.org/ApproxFun/ApproxFun.jl/jobs/168761460

**Comment by dlfivefifty** [comment]
I think move .julia aside, do 

```julia
Pkg.add("ApproxFun")
Pkg.checkout("ApproxFun","development")
Pkg.test("ApproxFun")
```

**Comment by marcusdavidwebb** [comment]
INFO: Testing ApproxFun
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
Domain tests
Error During Test
  Test threw an exception of type ErrorException
  Expression: Infinity(true) + Infinity(true) == Infinity(true)
  + not defined for ApproxFun.Infinity{Bool}
   in +(::ApproxFun.Infinity{Bool}, ::ApproxFun.Infinity{Bool}) at ./promotion.jl:255
   in include_from_node1(::String) at ./loading.jl:488
   in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   in process_options(::Base.JLOptions) at ./client.jl:262
   in _start() at ./client.jl:318
   in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
ERROR: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Error) at ./test.jl:397
 in do_test(::Base.Test.Threw, ::Expr) at ./test.jl:281
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/marcus/.julia/v0.5/ApproxFun/test/runtests.jl, in expression starting on line 12
==============================[ ERROR: ApproxFun ]==============================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/marcus/.julia/v0.5/ApproxFun/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: ApproxFun had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258

**Comment by dlfivefifty** [comment]
That's after moving the .julia folder away?

**Comment by marcusdavidwebb** [comment]
Ah I see what you mean now. All tests passed. I'll reinstall everything tomorrow morning and get back to you.

**Comment by dlfivefifty** [comment]
OK glad to hear.

After looking through the code, I realized the `promote_rule` overrides are inconsistent with the `+` overrides:

```julia
promote_type(Float64,Infinity{Bool})  # returns Float64
convert(Float64,∞)  # returns Inf
1.0+∞   # returns ∞, not Inf
```

Inconsistencies in type promotion seem to be the best way to trigger bugs in Julia's type inference code (I think it is roughly equivalent to Julia developers calling `convert(T,x)` and assuming it returns type `T` when they should have called `convert(T,x)::T`).  So it's possible that another package was triggering the known 0.5 type inference bug which interacted with the inconsistency in the overrides.

I think it should be fixed to do the following:

```julia
promote_type(Int,Infinity{B})  # returns Number
promote_type(Float64,Infinity{B})  # returns Float64
promote_type(Complex128,Infinity{B})  # returns Complex128

1 + ∞  # returns ∞
1.0 + ∞  # returns Inf
(1.0+1.0im) + ∞  # returns Inf + 1.0im
1.0 + Infinity(0.2)  # returns exp(0.2im)*Inf == Inf + Inf*im
```

**Comment by dlfivefifty** [comment]
The last one is a bit questionable as `promote_type` always promotes "up" in the sense that we don't throw out information, but in the last case we lose the argument of the infinity.....so it might be better if `promote_type(Complex128,Infinity)` also returns `Number`.

**Comment by marcusdavidwebb** [comment]
Everything works now, but I haven't installed all of the packages I once had. Who knows which package causes the bug?

**Comment by dlfivefifty** [comment]
Shit, my sarcastic response disappeared while writing it...

The jist: its  beta software

**Comment by marcusdavidwebb** [comment]
FYI it's happened again. Trying to find out which package it is that is causing this issue.

**Comment by dlfivefifty** [comment]
Can you try commenting out the convert and promote routines and see if that fixes things?

**Comment by marcusdavidwebb** [comment]
That fixed things.

**Comment by marcusdavidwebb** [comment]
Just pushed the change.

**Comment by marcusdavidwebb** [comment]
Didn't have an SSH key on this new laptop... duh.

**Comment by dlfivefifty** [comment]
I fixed your push by promoting to `Number`.  This is needed so that [1,∞] works.  (I'm confused that the fact they are both <: Number isn't recognized automatically.)  I also overrode ==.

  Can you pull and try again?

**Comment by marcusdavidwebb** [comment]
This works now. Cheers.
