### ISSUE TITLE
Fix Fourier transform with even length vectors

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#403]
Adding spacestest has found some bugs, not suprisingly.  I'm not sure if this is the fault of interlace! @MikaelSlevinsky  or was there before...

**Comment by dlfivefifty** [comment]
I'll try to fix it after lunch.

**Comment by dlfivefifty** [comment]
Hmm, I think this isn't actually a bug but a conceptual problem:  the following is surprising

```julia
S=Fourier()
pts = points(S,4)
itransform(S,[0.,0.,0.,1.]) ≠ sin(2pts) 
```

The issue is that `norm(sin(2pts)) == 0.` hence the transform is not invertible if it's consistent with evaluation.

I wonder if you using a shifted grid makes a difference....

**Comment by dlfivefifty** [comment]
I added `invertibletransform=false` to Fourier tests.   I think I can close this (though it seems as though there's a conceptual issue I'm not sure about.)

**Comment by MikaelSlevinsky** [comment]
I get
```julia
julia> using ApproxFun

julia> S=Fourier()
Fourier(【-3.141592653589793,3.141592653589793❫)

julia> pts = points(S,4)
4-element Array{Float64,1}:
 -3.14159
 -1.5708 
  0.0    
  1.5708 

julia> ApproxFun.itransform(S,[0.,0.,0.,1.])
4-element Array{Float64,1}:
  2.44929e-16
 -1.22465e-16
  0.0        
  1.22465e-16

julia> sin(2pts)
4-element Array{Float64,1}:
  2.44929e-16
 -1.22465e-16
  0.0        
  1.22465e-16

julia> norm(sin(2pts))
2.9997597730436923e-16

```
so the norm isn't exactly zero.
