### ISSUE TITLE
How to construct an interpolating function for a given set of sampled data

### ISSUE THREAD

**Issue by BoundaryValueProblems** [ApproxFun/ApproxFun.jl#425]
I want to construct a function on 1D interval _[a,b]_ that interpolates a given set of data points. Let _x<sub>i</sub>_ be an _i_-th sample point on this interval and let _f<sub>i</sub>_ be a sampled value of an unknown function _f_ at _x=x<sub>i</sub> , i=1:N_. (Typically, _{x<sub>i</sub>}_ are equispaced points, e.g., _x<sub>i</sub> = a+(i-0.5)*h_ where _h=(b-a)/N_). Now, here is what I did:
```julia
# Assume a vector of the sample point coordinates xs, that of the sampled values fs, and the value of a and b are given.
D = Interval([a,b])
f=Fun(x->bary(fs, xs, x),D)
```
By plotting this function ```f``` together with the samples ```(xs,fs)```, this ```f``` looks nicely interpolating these data points.  Is this what such an interpolation function should be constructed? In other words, Is using ```bary()``` provided by ApproxFun a most natural way to construct such an interpolating function?
Or is there any better or recommended way to construct an interpolating function?

Another important question is: how can I do the same on a 2D domain? If I have a set of sample points on a 2D rectangle and sample values on them, how can I construct a 2D interpolating function?

Thanks!
BVPs

**Comment by dlfivefifty** [comment]
I started a FAQ that addresses this.  2D would be the same as 1D:

https://github.com/ApproxFun/ApproxFun.jl/blob/development/docs/src/faq.md

**Comment by BoundaryValueProblems** [comment]
Thanks a lot!
BVPs

**Comment by BoundaryValueProblems** [comment]
Dear dlfivefifty,
It would be really great if you could add a 2D interpolation example in the FAQ along with the 1D case since such an example would help users understand how to set up, manipulate, and organize 2D grids and functions on them.
Thanks!
BVPs

**Comment by dlfivefifty** [comment]
Will do!  

I worked a bit on the docs this week.  Any suggestions you have are very much appreciated.
