### ISSUE TITLE
Rename `Interval` to `Segment`

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#429]
I just realized that `Interval` really means line segment, which can lead to confusion on how to interpret `Interval(1,0)`, especially as its inconsistent with IntervalSets:

https://github.com/JuliaMath/IntervalSets.jl/issues/8

I proposed renaming `Interval` as `Segment`.  Any thoughts?  @MikaelSlevinsky @marcusdavidwebb 

I'd rather do this sooner than later.  Luckily, this is a trivial find-all refactoring job.

**Comment by MikaelSlevinsky** [comment]
There could still be a segment constructor `Interval(a..b)` for real endpoints, right?

`PeriodicInterval` -> `PeriodicSegment` or `Torus`?
`IntervalCurve` -> `OpenCurve`?
`PeriodicCurve` -> `ClosedCurve`?

**Comment by dlfivefifty** [comment]
I think `Interval(a..b)` will be unnecessary: `a..b` will return an `IntervalSets.ClosedInterval` (to maintain 0.4 compatibility, it returns an `ApproxFun.ClosedInterval` at the moment), and `Domain(a..b)` will convert to a `Segment(a,b)`.

The issue at the moment is with `1 .. -1`.   `IntervalSets.ClosedInterval` interprets this as an empty set, while ApproxFun interprets as an oriented line segment from 1 to -1.  

I'm not sure reverse orientation is that common usage.... One option is to add a unicode symbol for oriented line segment.  Therefore, the following behaviour would occur:

```julia
Domain(0..1)     # returns Segment(0,1)
Domain(0..Inf)  # returns Ray()
Domain(0..0)    # returns Point(0)
Domain(0.. -1)  # returns EmptyDomain()
Domain(0..(1+im))  # returns ??  Complex intervals may mean a square in the complex plane

0⥛1     # returns Segment(0,1)
0⥛Inf  # returns Ray()
0⥛0    # returns Point(0) ?
0⥛-1   # returns Segment(0,-1)
0⥛im  # returns Segment(0,im)
```

**Comment by dlfivefifty** [comment]
That being said, I'm not convinced about the current conflation of `Domain` and maps from a canonical domain.  Here's a reference to a proposal

https://github.com/ApproxFun/ApproxFun.jl/issues/133

and to a package that represents only domains, and could be utilized:

https://github.com/zenna/AbstractDomains.jl

It might be best to leave the current behaviour for the time being to think about whether maps and domains should be two different concepts (in which case, we could add to AbstractDomains.jl support for segments, rays, etc. without including the `fromcanonical`, `tocanonical`, orientation, etc. concepts.
