### ISSUE TITLE
solving system of Funs

### ISSUE THREAD

**Issue by goretkin** [ApproxFun/ApproxFun.jl#77]
Is something like this possible?

```julia

d = Interval(0.,50.)
D = diff(d)
t = Fun(identity,d)

F = D^2 +.5D + 1
BC = [ldirichlet(d), lneumann(d)]
BC0 = [1.0, 0.0]
x = [BC, F]\[BC0, 0.0] #evolution of undriven equation x'' + .5x' + x = 0, works beautifully



A= [  ldirichlet(d)   0;
        lneumann(d)     0;
        rdirichlet(d)   0;
        F               -1; ] 

b = [1.0; 0.0; 2.0; 0.0]

xu = A\b 
```

`xu` should be two Funs corresponding to `x'' + .5x' + x = u` with the desired boundary conditions.

Does that seem reasonable?

**Comment by dlfivefifty** [comment]
I don't think your original equation is well-posed: given any solution pair (x,u) and function p that satisfies the boundary conditions (e.g., p(x)=x^2*(x-50), then (x+p,u+p''+.5p'+p) is also a solution to the original equation.

**Comment by goretkin** [comment]
yes, you are correct, it's not well-posed. It's still a linear problem and you mentioned that approxfun would regularize by finding the smoothest (probably the smallest L2 norm on the coefficients?) function.

I hope to still return to this one day!

**Comment by dlfivefifty** [comment]
That's only when the operator is banded.  If we interlace this operator, it would be "skew-banded" in the sense that it's banded around the entries that grow 2x for columns and 1x for rows

**Comment by goretkin** [comment]
Ah, I can see why the interlaced operator is skew-banded. But I don't understand what that means for the type of the solution it returns. Shouldn't it be possible to produce a minimum-norm solution either way?

(In reality, for this kind of control problem, you'd have some additive cost on u to make the problem well-posed, but there's probably an additive cost that corresponds to the minimum-norm Chebyshev coefficients.)

**Comment by dlfivefifty** [comment]
It's because there is only currently adaptiveqr for "BandedOperator".  Adding a SkewBandedOperator may be worthwhile.

**Comment by dlfivefifty** [comment]
This is now implemented in development branch!  (Ignore what I said about SkewBandedOperator, it recognizes that ConstantSpace should just append columns).  

Though you need to put the constant terms in the first column:

d = Interval(0.,50.)
D = Derivative(d)
t = Fun(identity,d)

F = D^2 +.5D + 1
BC = [ldirichlet(d), lneumann(d)]
BC0 = [1.0, 0.0]
x = [BC, F]\[BC0, 0.0] #evolution of undriven equation x'' + .5x' + x = 0, works beautifully


A= [0  ldirichlet(d);
    0    lneumann(d);
    0    rdirichlet(d);
    -1    F; ] 


u,x=A\[1.,0.,2.,0.]

norm(F*x-u)  # is ~zero

**Comment by dlfivefifty** [comment]
Also ignore the comment about it not being well-posedness: it is when u is assumed to be constant.
