### ISSUE TITLE
ldirichlet(d) and evaluate(d,d.a) behave differently 

### ISSUE THREAD

**Issue by goretkin** [ApproxFun/ApproxFun.jl#79]
Is there a reason why these shouldn't be identical operators
```julia
julia> evaluate(d,d.a)
Evaluation{UltrasphericalSpace{0},Float64,Float64}(UltrasphericalSpace{0}(Interval{Float64}(0.0,50.0)),0.0,0)

julia> ldirichlet(d)
Evaluation{UltrasphericalSpace{0},Bool,Float64}(UltrasphericalSpace{0}(Interval{Float64}(0.0,50.0)),false,0)
```

for any d, in this case `d=Interval(0.,50.)`

At least they should behave the same, but something is up here
```julia
d = Interval(0.,50.)
D = diff(d)
t = Fun(identity,d)

F = D^2 +.5D + 1
BC_test1 = [evaluate(d,0.), evaluate(d,0.)*D]
BC_test2 = [ldirichlet(d), lneumann(d)]
BC0 = [1.0, 0.0]

x1 = [BC_test1, F]\[BC0, 0.0]
x2 = [BC_test2, F]\[BC0, 0.0]
```
```julia
julia> norm(x1-x2)
0.9875181589473826
```

 `ldirichlet(d)` and `evaluate(d,d.a)` behave differently and/or  `lneumann(d)` and `evaluate(d,d.a) * D`

**Comment by goretkin** [comment]
I'm curious why there is an approximate check (though maybe I'm misunderstanding). Aren't these boundary conditions numerically identical?

**Comment by dlfivefifty** [comment]
Hmm, it looks like the actual bug was already fixed.

	I’ll leave the approximate check since otherwise Evaluation(d,0.,1) is not implemented yet.
