### ISSUE TITLE
Change to first kind Chebyshev points

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/ApproxFun.jl#81]
Fun(x->x<0?0:1,[-1.,0.,1.])

breaks cause second kind points evaluate at endpoints.  I can't see a reason not to use first kind points which avoid endpoints.

**Comment by dlfivefifty** [comment]
I keep running into issues with this one so I'll take care of it soon

**Comment by MikaelSlevinsky** [comment]
If we change to first kind points, we should be able to use the function values to implement endpoint singularity detection.

**Comment by MikaelSlevinsky** [comment]
On the other hand, Chebyshev points of the first kind do not nest nearly as efficiently as points of the second kind. On branch:

```julia
chebyshevpoints(2)
chebyshevpoints(6)
chebyshevpoints(18)
```

```julia
chebyshevpoints(5;kind=2)
chebyshevpoints(9;kind=2)
chebyshevpoints(17;kind=2)
```

**Comment by MikaelSlevinsky** [comment]
This can now be closed. Further advantages include:
- roots of large `Fun`s based on Chebyshev series are about 40% faster
- can create `Fun`s with removable singularities at the middle of the interval
```julia
Fun(x->bessely0(abs(x))-2/π*besselj0(x)*log(abs(x)),Chebyshev([-2.,2.]))
```
Recycling function samples is another issue.
